//----------------------------------------------------------------------
// MActionResultDef.h
//----------------------------------------------------------------------

#ifndef __MACTIONRESULTDEF_H__
#define __MACTIONRESULTDEF_H__

//----------------------------------------------------------------------
//

//
//----------------------------------------------------------------------

typedef	unsigned short TYPE_ACTIONRESULTID;
#define	SIZE_ACTIONRESULTID			2
#define	ACTIONRESULTID_NULL			0xFFFF

	
//------------------------------------------------------

//------------------------------------------------------
enum	ACTIONRESULTNODE_TYPE
{
	ACTIONRESULTNODE_NULL = 0,

	ACTIONRESULTNODE_ACTIONINFO,			
	ACTIONRESULTNODE_CHANGE_POSITION,		
	ACTIONRESULTNODE_CHANGE_STATUS,			
	ACTIONRESULTNODE_CREATURE_DIE,			
	ACTIONRESULTNODE_CREATURE_BURROW,		
	ACTIONRESULTNODE_CREATURE_INVISIBLE,	
	ACTIONRESULTNODE_CREATURE_VISIBLE,		
	ACTIONRESULTNODE_CREATURE_SNIPPING,		
	ACTIONRESULTNODE_ADD_EFFECTSTATUS,		
	ACTIONRESULTNODE_CHANGE_CREATURE_TYPE,	
	ACTIONRESULTNODE_SUMMON_CASKET,			
	ACTIONRESULTNODE_OPEN_CASKET,			
	ACTIONRESULTNODE_CREATURE_TURNING,		
	ACTIONRESULTNODE_REMOVE_ITEM_IN_INVENTORY,			
	ACTIONRESULTNODE_CHANGE_ITEM_OPTION_IN_INVENTORY,	
	ACTIONRESULTNODE_FAKE_DIE,				
	ACTIONRESULTNODE_EVENT,					
	ACTIONRESULTNODE_CHANGE_ITEM_GENDER,

	ACTIONRESULTNODE_MAX
};


#endif