//----------------------------------------------------------------------
// MEffectGeneratorDef.h
//----------------------------------------------------------------------

#ifndef __MEFFECTGENERATORDEF_H__
#define __MEFFECTGENERATORDEF_H__

//----------------------------------------------------------------------
// class ID
//----------------------------------------------------------------------
enum ENUM_EFFECTGENERATORID 
{
	EFFECTGENERATORID_ATTACK_CREATURE = 0,
	EFFECTGENERATORID_ATTACK_ZONE,
	EFFECTGENERATORID_ATTACK_ZONE_PARABOLA,
	EFFECTGENERATORID_STOP_ZONE,
	EFFECTGENERATORID_RISING,
	EFFECTGENERATORID_FALLING,
	EFFECTGENERATORID_ATTACK_CREATURE_PARABOLA,
	EFFECTGENERATORID_ATTACH_CREATURE,
	EFFECTGENERATORID_ATTACH_CREATURE_GROUND,
	EFFECTGENERATORID_STOP_ZONE_CROSS,
	EFFECTGENERATORID_STOP_ZONE_X,
	EFFECTGENERATORID_STOP_ZONE_RECT,
	EFFECTGENERATORID_STOP_ZONE_RHOMBUS,
	EFFECTGENERATORID_RIPPLE_ZONE,
	EFFECTGENERATORID_RIPPLE_ZONE_WIDE,
	EFFECTGENERATORID_STOP_INVENTORY,
	EFFECTGENERATORID_STOP_ZONE_MULTIPLE,
	EFFECTGENERATORID_MULTIPLE_FALLING,
	EFFECTGENERATORID_STOP_ZONE_RANDOM,
	EFFECTGENERATORID_ATTACH_ZONE,
	EFFECTGENERATORID_STOP_ZONE_WALL,	
	EFFECTGENERATORID_RIPPLE_ZONE_PIXEL,	
	EFFECTGENERATORID_STOP_ZONE_SELECTABLE,	
	EFFECTGENERATORID_ATTACH_ZONE_SELECTABLE,	
	EFFECTGENERATORID_SPREAD_OUT,
	EFFECTGENERATORID_BLOODY_WALL,
	EFFECTGENERATORID_ATTACK_CREATURE_HOMING,
	EFFECTGENERATORID_BLOODY_WAVE,
	EFFECTGENERATORID_AROUND_ZONE,
	EFFECTGENERATORID_STOP_ZONE_EMPTY_CROSS,			
	EFFECTGENERATORID_STOP_ZONE_EMPTY_RECT,				
	EFFECTGENERATORID_STOP_ZONE_EMPTY_HORIZONTAL_WALL,	
	EFFECTGENERATORID_STOP_ZONE_EMPTY_VERTICAL_WALL,	
	EFFECTGENERATORID_ATTACK_ZONE_BOMB,					
	EFFECTGENERATORID_ATTACH_CREATURE_ORBIT,			
	EFFECTGENERATORID_METEOR_DROP,						
	EFFECTGENERATORID_BLOODY_BREAKER,					
	EFFECTGENERATORID_ATTACH_ZONE_AROUND,				
	EFFECTGENERATORID_ATTACK_ZONE_RECT,
	EFFECTGENERATORID_FOLLOW_PATH,						
	EFFECTGENERATORID_FIRE_PIECING,
	EFFECTGENERATORID_SKIP_DRAW,
	EFFECTGENERATORID_PLAYING_WITH_FIRE,
	
	MAX_EFFECTGENERATORID	
};


#endif