
 

//----------------------------------------------------------------------
// MGameStringTable.h
//----------------------------------------------------------------------

#ifndef __MGAMESTRINGTABLE_H__
#define	__MGAMESTRINGTABLE_H__

#include "MStringArray.h"

extern MStringArray*		g_pGameStringTable;
//2004, 6, 18, sobeit add start - about nick name string table
extern MStringArray*		g_pNickNameStringTable;
//2004, 6, 18, sobeit add end - about nick name string table
#ifndef __GAME_CLIENT__
	extern void				InitGameStringTable();
#endif

//----------------------------------------------------------------------
//----------------------------------------------------------------------
enum GAME_STRINGID
{
	STRING_NETWORK_CONDITION_BAD,
	STRING_RESURRECTION_AFTER_SECONDS,
	STRING_DRAW_ZONE_NAME,
	STRING_DRAW_GAME_DATE,
	STRING_DRAW_GAME_TIME,
	STRING_DRAW_ITEM_NAME_MONEY,

	STRING_USER_REGISTER_DENY,
	STRING_USER_REGISTER_HOMEPAGE,
	STRING_USER_REGISTER_EMPTY_FIELD,
	STRING_USER_REGISTER_INVALID_ID,
	STRING_USER_REGISTER_ID_LENGTH,
	STRING_USER_REGISTER_ID_SPECIAL,
	STRING_USER_REGISTER_PASSWORD_LENGTH,
	STRING_USER_REGISTER_PASSWORD_SPECIAL,
	STRING_USER_REGISTER_PASSWORD_NUMBER,
	STRING_USER_REGISTER_NAME_LENGTH,
	STRING_USER_REGISTER_INVALID_SSN,
	STRING_USER_REGISTER_SSN_FORMAT,

	STRING_MESSAGE_CANNOT_BUY_NO_SPACE,
	STRING_MESSAGE_CANNOT_BUY_NO_MONEY,
	STRING_MESSAGE_CANNOT_BUY_NO_ITEM,
	STRING_MESSAGE_CANNOT_SELL,
	STRING_MESSAGE_CANNOT_REPAIR,
	STRING_MESSAGE_CANNOT_SILVERING,
	STRING_MESSAGE_CANNOT_BUY_MORE,
	STRING_MESSAGE_CANNOT_STORAGE,
	STRING_MESSAGE_STORAGE_BUY,
	STRING_MESSAGE_NO_STORAGE,
	STRING_MESSAGE_TRADE_REJECTED,
	STRING_MESSAGE_TRADE_NOBODY,		
	STRING_MESSAGE_TRADE_CANNOT_ON_MOTORCYCLE,
	STRING_MESSAGE_TRADE_SAFETY_ZONE_ONLY,
	STRING_MESSAGE_TRADE_BUSY,
	STRING_MESSAGE_CANNOT_TRADE,
	STRING_MESSAGE_CANNOT_TRADE_ALREADY_TRADING,
	STRING_MESSAGE_CANNOT_TRADE_NO_SPACE,
	STRING_MESSAGE_SKILL_DIFFER_DOMAIN,
	STRING_MESSAGE_SKILL_EXCEED_LEVEL,
	STRING_MESSAGE_SKILL_CANNOT_LEARN,
	STRING_MESSAGE_SKILL_NOT_SUPPORT,
	STRING_MESSAGE_FIND_MOTOR_NO_WHERE,
	STRING_MESSAGE_FIND_MOTOR_NO_KEY,
	STRING_MESSAGE_FIND_MOTOR_OK,
	STRING_MESSAGE_CANNOT_USE_BONUS_POINT,
	STRING_MESSAGE_WHAT_SKILL_TO_LEARN,
	STRING_MESSAGE_NO_SKILL_TO_LEARN,
	STRING_MESSAGE_NEW_SKILL_AVAILABLE,
	STRING_MESSAGE_NEW_DOMAIN_LEVEL_1,
	STRING_MESSAGE_NEW_DOMAIN_LEVEL_2,
	STRING_MESSAGE_CANNOT_MOVE_SAFETY_ZONE_RELIC,			

	STRING_MESSAGE_TEAM_REGIST_FAIL_ALREADY_JOIN,			
	STRING_MESSAGE_TEAM_REGIST_FAIL_QUIT_TIMEOUT,			
	STRING_MESSAGE_TEAM_REGIST_FAIL_CANCEL_TIMEOUT,		
	STRING_MESSAGE_TEAM_REGIST_FAIL_LEVEL,				
	STRING_MESSAGE_TEAM_REGIST_FAIL_MONEY,				
	STRING_MESSAGE_TEAM_REGIST_FAIL_FAME,					
	STRING_MESSAGE_TEAM_REGIST_FAIL_NAME,					
	STRING_MESSAGE_TEAM_REGIST_FAIL_DENY,					

	STRING_MESSAGE_TEAM_STARTING_FAIL_ALREADY_JOIN,		
	STRING_MESSAGE_TEAM_STARTING_FAIL_QUIT_TIMEOUT,		
	STRING_MESSAGE_TEAM_STARTING_FAIL_CANCEL_TIMEOUT,		
	STRING_MESSAGE_TEAM_STARTING_FAIL_LEVEL,				
	STRING_MESSAGE_TEAM_STARTING_FAIL_MONEY,				
	STRING_MESSAGE_TEAM_STARTING_FAIL_FAME,				
	STRING_MESSAGE_TEAM_STARTING_FAIL_DENY,					

	STRING_MESSAGE_CLAN_REGIST_FAIL_ALREADY_JOIN,			
	STRING_MESSAGE_CLAN_REGIST_FAIL_QUIT_TIMEOUT,			
	STRING_MESSAGE_CLAN_REGIST_FAIL_CANCEL_TIMEOUT,		
	STRING_MESSAGE_CLAN_REGIST_FAIL_LEVEL,				
	STRING_MESSAGE_CLAN_REGIST_FAIL_MONEY,				
	STRING_MESSAGE_CLAN_REGIST_FAIL_FAME,					
	STRING_MESSAGE_CLAN_REGIST_FAIL_NAME,					
	STRING_MESSAGE_CLAN_REGIST_FAIL_DENY,					

	STRING_MESSAGE_CLAN_STARTING_FAIL_ALREADY_JOIN,		
	STRING_MESSAGE_CLAN_STARTING_FAIL_QUIT_TIMEOUT,		
	STRING_MESSAGE_CLAN_STARTING_FAIL_CANCEL_TIMEOUT,		
	STRING_MESSAGE_CLAN_STARTING_FAIL_LEVEL,				
	STRING_MESSAGE_CLAN_STARTING_FAIL_MONEY,				
	STRING_MESSAGE_CLAN_STARTING_FAIL_FAME,				
	STRING_MESSAGE_CLAN_STARTING_FAIL_DENY,					

	STRING_MESSAGE_GUILD_REGIST_FAIL_INTRO,					

	STRING_STATUS_HP_MAX_1,
	STRING_STATUS_HP_MAX_2,
	STRING_STATUS_MP_MAX_1,
	STRING_STATUS_MP_MAX_2,
	STRING_STATUS_STR_1,
	STRING_STATUS_STR_2,
	STRING_STATUS_DEX_1,
	STRING_STATUS_DEX_2,
	STRING_STATUS_INT_1,
	STRING_STATUS_INT_2,
	STRING_STATUS_LEVEL,
	STRING_LEARN_SKILL,
	STRING_CHANGE_ALIGNMENT,
	STRING_CHANGE_ALIGNMENT2,
	STRING_CHANGE_TO_BAD_ALIGNMENT,
	STRING_CHANGE_TO_GOOD_ALIGNMENT,

	STRING_ERROR_INVALID_ID_PASSWORD,
	STRING_ERROR_ALREADY_CONNECTED,
	STRING_ERROR_ALREADY_REGISTER_ID,
	STRING_ERROR_ALREADY_REGISTER_SSN,
	STRING_ERROR_EMPTY_ID,
	STRING_ERROR_SMALL_ID_LENGTH,
	STRING_ERROR_EMPTY_PASSWORD,
	STRING_ERROR_SMALL_PASSWORD_LENGTH,
	STRING_ERROR_EMPTY_NAME,
	STRING_ERROR_EMPTY_SSN,
	STRING_ERROR_INVALID_SSN,
	STRING_ERROR_NOT_FOUND_PLAYER,
	STRING_ERROR_NOT_FOUND_ID,
	STRING_ERROR_LOGIN_DENY,
	STRING_ERROR_ETC_ERROR,
	STRING_ERROR_NOT_ALLOW_ACCOUNT,
	STRING_ERROR_NOT_PAY_ACCOUNT,

	STRING_MESSAGE_ITEM_BROKEN,	
	STRING_MESSAGE_WHISPER_FAILED,
	STRING_MESSAGE_WHISPER_SELF,
	STRING_MESSAGE_CHAT_IGNORE,
	STRING_MESSAGE_CHAT_ACCEPT,
	STRING_MESSAGE_CHAT_IGNORE_ALL,
	STRING_MESSAGE_CHAT_ACCEPT_ALL,
	STRING_MESSAGE_CHAT_BE_GOOD,
	STRING_MESSAGE_CHAT_ACCEPT_CURSE,
	STRING_MESSAGE_CHAT_FILTER_CURSE,
	STRING_MESSAGE_CANNOT_LOGOUT_DIED,
	STRING_MESSAGE_CANNOT_GLOBAL_SAY,

	STRING_MESSAGE_WAIT,

	STRING_MESSAGE_CONNECTING_SERVER,

	STRING_MESSAGE_DONATION_OK,
	STRING_MESSAGE_DONATION_FAIL,

	STRING_MESSAGE_PARTY_REJECTED,
	STRING_MESSAGE_PARTY_NOBODY,		
	STRING_MESSAGE_PARTY_SAFETY_ZONE_ONLY,
	STRING_MESSAGE_PARTY_BUSY,
	STRING_MESSAGE_RACE_DIFFER,
	STRING_MESSAGE_NOT_NORMAL_FORM,
	STRING_MESSAGE_NO_AUTHORITY,
	STRING_MESSAGE_ERROR_PARTY,
	STRING_MESSAGE_KICK_PARTY_MEMBER_OK,
	STRING_MESSAGE_KICKED_FROM_PARTY,
	STRING_MESSAGE_KICK_PARTY_MEMBER,
	STRING_MESSAGE_REMOVE_PARTY,
	STRING_MESSAGE_REMOVE_PARTY_HIMSELF,
	STRING_MESSAGE_REMOVE_PARTY_MYSELF,
	STRING_MESSAGE_IN_ANOTHER_PARTY,
	STRING_MESSAGE_PARTY_FULL,
	STRING_MESSAGE_SOMEONE_JOINED_PARTY,

	STRING_MESSAGE_LOGOUT_AFTER_SECOND,

	STRING_MESSAGE_CANNOT_BUY_NO_STAR,
	STRING_MESSAGE_CANNOT_BUY,

	STRING_MESSAGE_CAN_REGISTER_NAME,

	STRING_MESSAGE_HELP_KEY,
	STRING_MESSAGE_HOW_TO_GET_BASIC_WEAPON,
	STRING_MESSAGE_WAIT_FOR_CHARACTER_SELECT_MODE,

	STRING_MESSAGE_ITEM_TO_ITEM_IMPOSIBLE,

	
	UI_STRING_MESSAGE_ONLY_PICK_UP_ITEM_ONE,       
	UI_STRING_MESSAGE_CAN_ENCHANT,					
	UI_STRING_MESSAGE_SELL_CONFIRM,					
	UI_STRING_MESSAGE_ALL_SELL_CONFIRM,				
	UI_STRING_MESSAGE_ALL_PRICE,					
	UI_STRING_MESSAGE_REPAIR_CONFIRM,				
	UI_STRING_MESSAGE_CLICK_TRADE_ITEM,				
	UI_STRING_MESSAGE_CLICK_REPAIR_ITEM,			
	UI_STRING_MESSAGE_CLICK_OK_BUTTON_TO_END,		
	UI_STRING_MESSAGE_THIS_ITEM_REPAIR_CONFIRM,		
	UI_STRING_MESSAGE_THIS_ITEM_CHARGE_CONFIRM,		
	UI_STRING_MESSAGE_THIS_ITEM_SILVERING_CONFIRM,	
	UI_STRING_MESSAGE_CLICK_SILVERING_ITEM,			
	UI_STRING_MESSAGE_SHOW_ALPHA_WINDOW,			
	UI_STRING_MESSAGE_SHOW_NO_ALPHA_WINDOW,			
	UI_STRING_MESSAGE_CAN_EQUIP,					
	UI_STRING_MESSAGE_CANNOT_EQUIP,					
	UI_STRING_MESSAGE_THROW_MONEY,					
	UI_STRING_MESSAGE_SHOW_ITEM_DESCRIPTION,		
	UI_STRING_MESSAGE_DEPOSIT_MONEY,				
	UI_STRING_MESSAGE_INVITE_PARTY,					
	UI_STRING_MESSAGE_REQUEST_PARTY,				
	UI_STRING_MESSAGE_RESURRECTION,					
	UI_STRING_MESSAGE_EVACUATION,					
	UI_STRING_MESSAGE_CANNOT_UP_LEVEL,				
	UI_STRING_MESSAGE_CANNOT_UP_STAT,				
	UI_STRING_MESSAGE_TEAM_INFO_JOIN,				

	// UI TIP
	UI_STRING_MESSAGE_TIP_SELL_ALL_VAMPIRE_HEAD,	
	UI_STRING_MESSAGE_TIP_REPAIR_ALL_ITEM,			


	UI_STRING_MESSAGE_AUTO_HIDE_ON,					
	UI_STRING_MESSAGE_AUTO_HIDE_OFF,				
	UI_STRING_MESSAGE_GAME_MENU,					
	UI_STRING_MESSAGE_MENU,							
	UI_STRING_MESSAGE_EXP,							
	UI_STRING_MESSAGE_TEAM,							
	UI_STRING_MESSAGE_MESSAGE,						
	UI_STRING_MESSAGE_HELP,							
	UI_STRING_MESSAGE_INVENTORY,					
	UI_STRING_MESSAGE_GEAR_WINDOW,					
	UI_STRING_MESSAGE_INFO_WINDOW,					
	UI_STRING_MESSAGE_PARTY_WINDOW,					
	UI_STRING_MESSAGE_QUEST_WINDOW,					
	UI_STRING_MESSAGE_TEAM_INFO,					
	UI_STRING_MESSAGE_TEAM_MEMBER_LIST,				
	UI_STRING_MESSAGE_BASIC_HELP,					
	UI_STRING_MESSAGE_CHATTING_HELP,				
	UI_STRING_MESSAGE_WAR_HELP,						
	UI_STRING_MESSAGE_SKILL_HELP,					
	UI_STRING_MESSAGE_TEAM_HELP,					
	UI_STRING_MESSAGE_CLAN,							
	UI_STRING_MESSAGE_CLAN_INFO,					
	UI_STRING_MESSAGE_CLAN_MEMBER_LIST,				
	UI_STRING_MESSAGE_CLAN_HELP,					
	UI_STRING_MESSAGE_MAGIC_HELP,					

	// Simple Info
	UI_STRING_MESSAGE_CURRENT_EXP,					
	UI_STRING_MESSAGE_NEXT_LEVEL,					
	UI_STRING_MESSAGE_LEFT_EXP,						

	// Inventory
	UI_STRING_MESSAGE_EQUIP_HELM,					
	UI_STRING_MESSAGE_EQUIP_NECKLACE,				
	UI_STRING_MESSAGE_EQUIP_ARMOR,					
	UI_STRING_MESSAGE_EQUIP_SHIELD,					
	UI_STRING_MESSAGE_EQUIP_WEAPON,					
	UI_STRING_MESSAGE_EQUIP_GLOVE,					
	UI_STRING_MESSAGE_EQUIP_BELT,					
	UI_STRING_MESSAGE_EQUIP_TROUSER,				
	UI_STRING_MESSAGE_EQUIP_BRACELET,				
	UI_STRING_MESSAGE_EQUIP_RING,					
	UI_STRING_MESSAGE_EQUIP_SHOES,					
	UI_STRING_MESSAGE_EQUIP_VAMPIRE_COAT,			
	UI_STRING_MESSAGE_EQUIP_EARRING,				
	UI_STRING_MESSAGE_EQUIP_AMULET,					
	UI_STRING_MESSAGE_FIRST_GEAR_SET,				
	UI_STRING_MESSAGE_SECOND_GEAR_SET,				

	// Chating Description
	UI_STRING_MESSAGE_SPECIAL_CHARACTER,			
	UI_STRING_MESSAGE_SET_LETTER_COLOR,				
	UI_STRING_MESSAGE_CHANGE_INPUT_LANGUAGE,		
	UI_STRING_MESSAGE_SHOW_WHISPER_ID,				
	UI_STRING_MESSAGE_NORMAL_CHATING,				
	UI_STRING_MESSAGE_ZONE_CHATTING,				
	UI_STRING_MESSAGE_WHISPER_CHATTING,				
	UI_STRING_MESSAGE_PARTY_CHATTING,				
	UI_STRING_MESSAGE_TEAM_CHATTING,				
	UI_STRING_MESSAGE_SHOW_NORMAL_CHATTING,			
	UI_STRING_MESSAGE_SHOW_ZONE_CHATTING,			
	UI_STRING_MESSAGE_SHOW_WHISPER_CHATTING,		
	UI_STRING_MESSAGE_SHOW_PARTY_CHATTING,			
	UI_STRING_MESSAGE_SHOW_TEAM_CHATTING,			
	UI_STRING_MESSAGE_NOT_SHOW_NORMAL_CHATTING,		
	UI_STRING_MESSAGE_NOT_SHOW_ZONE_CHATTING,		
	UI_STRING_MESSAGE_NOT_SHOW_WHISPER_CHATTING,	
	UI_STRING_MESSAGE_NOT_SHOW_PARTY_CHATTING,		
	UI_STRING_MESSAGE_NOT_SHOW_TEAM_CHATTING,		
	UI_STRING_MESSAGE_NOT_SHOW_CLAN_CHATTING,		
	UI_STRING_MESSAGE_SHOW_CLAN_CHATTING,			
	UI_STRING_MESSAGE_CLAN_CHATTING,				
	UI_STRING_MESSAGE_EXPEL,						
	UI_STRING_MESSAGE_SECEDE,						
	
	// Party
	UI_STRING_MESSAGE_SET_INVITE_DENY_MODE,			
	UI_STRING_MESSAGE_CANCEL_INVITE_DENY_MODE,		
	UI_STRING_MESSAGE_SET_JOIN_DENY_MODE,			
	UI_STRING_MESSAGE_CANCEL_JOIN_DENY_MODE,		
	

	// Level Up	
	UI_STRING_MESSAGE_UP_STR,						
	UI_STRING_MESSAGE_UP_DEX,						
	UI_STRING_MESSAGE_UP_INT,						

	
	// INFO WINDOW
	UI_STRING_MESSAGE_SHOW_SKILL_INFO_WINDOW,		
	UI_STRING_MESSAGE_SHOW_CHARACTER_INFO_WINDOW,	
	UI_STRING_MESSAGE_SHOW_MAGIC_INFO_WINDOW,		
	UI_STRING_MESSAGE_SHOW_ADVANTE_INFO_WINODW,		
	UI_STRING_MESSAGE_SHOW_BLADE_INFO,				
	UI_STRING_MESSAGE_SHOW_SWORD_INFO,				
	UI_STRING_MESSAGE_SHOW_GUN_INFO,				
	UI_STRING_MESSAGE_SHOW_HEAL_INFO,				
	UI_STRING_MESSAGE_SHOW_ENCHANT_INFO,			
	UI_STRING_MESSAGE_SHOW_ALL_INFO,				
	UI_STRING_MESSAGE_SHOW_POISON_INFO,				
	UI_STRING_MESSAGE_SHOW_ACID_INFO,				
	UI_STRING_MESSAGE_SHOW_CURSE_INFO,				
	UI_STRING_MESSAGE_SHOW_SUMMON_INFO,				
	UI_STRING_MESSAGE_SHOW_BLOOD_INFO,				
	UI_STRING_MESSAGE_SHOW_ESSENCE_INFO,			
	
	

	// SHOW HELP WINDOW
	UI_STRING_MESSAGE_SHOW_HELP_MAGIC_INFO_WINDOW,	
	UI_STRING_MESSAGE_SHOW_HELP_SKILL_INFO_WINDOW,	
	UI_STRING_MESSAGE_SHOW_HELP_INVENTORY_WINDOW,	
	UI_STRING_MESSAGE_SHOW_HELP_PARTY_MANAGER,		
	UI_STRING_MESSAGE_SHOW_HELP_CHARACTER_INFO_WINDOW,	
	UI_STRING_MESSAGE_SHOW_HELP_GEAR_WINDOW,			
	UI_STRING_MESSAGE_SHOW_HELP_STORAGE_WINDOW,			
	UI_STRING_MESSAGE_SHOW_HELP_SHOP_WINDOW,			
	UI_STRING_MESSAGE_DESC_SHOW_EXCHANGE_WINDOW,			
	


	// CLOSE WINDOW
	UI_STRING_MESSAGE_CLOSE_INVENTORY_WINDOW,			
	UI_STRING_MESSAGE_CLOSE_PARTY_MANAGER,				
	UI_STRING_MESSAGE_CLOSE_CHARACTER_INFO_WINDOW,		
	UI_STRING_MESSAGE_CLOSE_GEAR_WINDOW,				
	UI_STRING_MESSAGE_CLOSE_MAGIC_INFO_WINDOW,			
	UI_STRING_MESSAGE_CLOSE_SKILL_INFO_WINDOW,			
	UI_STRING_MESSAGE_CLOSE_DESC_WINDOW,				
	UI_STRING_MESSAGE_CLOSE_STORAGE_WINDOW,				
	UI_STRING_MESSAGE_CLOSE_SHOP_WINDOW,				
	UI_STRING_MESSAGE_CLOSE_BOOKCASE,					
	UI_STRING_MESSAGE_CLOSE_BOOK,						
	
	
	
	UI_STRING_MESSAGE_NOT_JOIN_ANY_TEAM,				
	UI_STRING_MESSAGE_NOT_JOIN_ANY_CLAN,				
	UI_STRING_MESSAGE_INFRA_RED_HELMET,					
	UI_STRING_MESSAGE_INFRA_HELMET,						
	UI_STRING_MESSAGE_QUIT_COMPUTER,					

	UI_STRING_MESSAGE_SHOW_NEXT_PAGE,					
	UI_STRING_MESSAGE_SHOW_PREV_PAGE,					


	UI_STRING_MESSAGE_ENG_STR,						// STR
	UI_STRING_MESSAGE_ENG_DEX,						// DEX
	UI_STRING_MESSAGE_ENG_INT,						// INT
	
	UI_STRING_MESSAGE_MASTER_NAME,					
	UI_STRING_MESSAGE_LIMIT_STRING_COUNT,			
	UI_STRING_MESSAGE_HELP_MESSAGE,					
	UI_STRING_MESSAGE_STR,							
	UI_STRING_MESSAGE_DEX,							
	UI_STRING_MESSAGE_INT,							
	UI_STRING_MESSAGE_HP,							
	UI_STRING_MESSAGE_MP,							
	UI_STRING_MESSAGE_ACCURACY,						
	UI_STRING_MESSAGE_DAMAGE,						
	UI_STRING_MESSAGE_AVOID,						
	UI_STRING_MESSAGE_DEFENCE,						
	UI_STRING_MESSAGE_ALIGNMENT,					

	UI_STRING_MESSAGE_ALIGN_VERY_BAD,				
	UI_STRING_MESSAGE_ALIGN_BAD,					
	UI_STRING_MESSAGE_ALIGN_NORMAL,					
	UI_STRING_MESSAGE_ALIGN_GOOD,					
	UI_STRING_MESSAGE_ALIGN_VERY_GOOD,				

	UI_STRING_MESSAGE_STR_PURE,						
	UI_STRING_MESSAGE_DEX_PURE,						
	UI_STRING_MESSAGE_INT_PURE,						
	UI_STRING_MESSAGE_STATUS_SUM_PURE,				
	UI_STRING_MESSAGE_STATUS_SUM,					

	UI_STRING_MESSAGE_SPEED_SLOW,					
	UI_STRING_MESSAGE_SPEED_NORMAL,					
	UI_STRING_MESSAGE_SPEED_FAST,					

	UI_STRING_MESSAGE_ATTACK_SPEED,					

	// HpBar	
	UI_STRING_MESSAGE_PASSIVE,						// "Passive"
	UI_STRING_MESSAGE_HAN_PASSIVE,					

	UI_STRING_MESSAGE_HPBAR_LEVEL_DESCRIPTION,		// "LEVEL:%d"
	UI_STRING_MESSAGE_HPBAR_EXP_DESCRIPTION,		
	UI_STRING_MESSAGE_HPBAR_MP_DESCRIPTION,			// "MP:%d/%d"
	UI_STRING_MESSAGE_HPBAR_HP_DESCRIPTION_WITH_SILVERING,			// "HP:%d/%d(S:%d)"
	UI_STRING_MESSAGE_HPBAR_HP_DESCRIPTION,							// "HP:%d/%d"	
	UI_STRING_MESSAGE_HPBAR_CHANGE_VAMPIRE_DAY,		
	UI_STRING_MESSAGE_HPBAR_CHANGE_VAMPIRE_HOUR,	
	UI_STRING_MESSAGE_HPBAR_CHANGE_VAMPIRE_MINUTE,	
	UI_STRING_MESSAGE_HPBAR_CHANGE_VAMPIRE_SOON,	
	UI_STRING_MESSAGE_HPBAR_SET_LARGE,				
	UI_STRING_MESSAGE_HPBAR_SET_SMALL,				
	UI_STRING_MESSAGE_HPBAR_SET_WIDTH,				
	UI_STRING_MESSAGE_HPBAR_SET_HEIGHT,				

	
	UI_STRING_MESSAGE_SHOW_WIDTH,					
	UI_STRING_MESSAGE_SHOW_HEIGHT,					

	// Guild
	UI_STRING_MESSAGE_SHOW_HELP,					
	UI_STRING_MESSAGE_CLOSE_WINDOW,					
	UI_STRING_MESSAGE_REGIST,						
	UI_STRING_MESSAGE_LIST_UP,						
	UI_STRING_MESSAGE_LIST_DOWN,					
	UI_STRING_MESSAGE_REFRESH_LIST,					
	UI_STRING_MESSAGE_SORT_TEAM_NAME,				
	UI_STRING_MESSAGE_SORT_LEADER_NAME,				
	UI_STRING_MESSAGE_SORT_EXPIRE_DATE,				
	UI_STRING_MESSAGE_SORT_NUMBER_MEMBER,			
	UI_STRING_MESSAGE_SORT_RANKING,					

	UI_STRING_MESSAGE_CHANGE_FIND_MODE,				
	UI_STRING_MESSAGE_FIND,							

	UI_STRING_MESSAGE_TEAM_GRADE_MASTER,			
	UI_STRING_MESSAGE_TEAM_GRADE_SUB_MASTER,		
	UI_STRING_MESSAGE_TEAM_GRADE_WAIT,				
	UI_STRING_MESSAGE_TEAM_GRADE_MEMBER,			

	UI_STRING_MESSAGE_TEAM_INFO_GRADE,				//Grade : %s
	UI_STRING_MESSAGE_TEAM_INFO_NAME,				//Name : %s
	UI_STRING_MESSAGE_TEAM_INFO_LEADER,				//Leader : %s
	UI_STRING_MESSAGE_TEAM_INFO_REG_FEE,			//Reg. Fee : $%s
	UI_STRING_MESSAGE_TEAM_INFO_MEMBERS,			//Members : "
	UI_STRING_MESSAGE_TEAM_INFO_INTRODUCTION,		//Introduction : "
	UI_STRING_MESSAGE_TEAM_INFO_CLAN_INTRODUCTION,	//Clan Introduction : "
	UI_STRING_MESSAGE_TEAM_INFO_TEAM_INTRODUCTION,	//Team Introduction : "
	UI_STRING_MESSAGE_TEAM_INFO_RANKING,			//Ranking : %d

	UI_STRING_MESSAGE_TEAM_INFO_TEAM_NAME,			//Team Name : %s"
	UI_STRING_MESSAGE_TEAM_INFO_CLAN_NAME,			//Clan Name : %s"
	UI_STRING_MESSAGE_TEAM_INFO_REGISTRATION_FEE,	//Registration Fee : $%s"
	UI_STRING_MESSAGE_TEAM_INFO_SELF_INTRODUCTION,	//Self Introduction : "

	UI_STRING_MESSAGE_UP,							
	UI_STRING_MESSAGE_DOWN,							
	UI_STRING_MESSAGE_TEAM_INFO_EXPEL,				
	UI_STRING_MESSAGE_TEAM_INFO_JOIN_ACCEPT,		
	UI_STRING_MESSAGE_TEAM_INFO_JOIN_DENY,			
	UI_STRING_MESSAGE_CANCEL,						

	
	// Zone Name

	UI_STRING_MESSAGE_LIMBOLAIR,					
	UI_STRING_MESSAGE_ESLANIA,						
	UI_STRING_MESSAGE_RODIN,						
	UI_STRING_MESSAGE_DROBETA,						
	UI_STRING_MESSAGE_PERONA,						
	UI_STRING_MESSAGE_TIMORE,						

	UI_STRING_MESSAGE_ZONEINFO_XY,					// X:%d Y:%d

	// Accelerator Name
	UI_STRING_MESSAGE_ACCELERATOR_NULL,				//"AcceleratorNULL",
	UI_STRING_MESSAGE_ACCELERATOR_F1,				//"F1",
	UI_STRING_MESSAGE_ACCELERATOR_F2,				//"F2",
	UI_STRING_MESSAGE_ACCELERATOR_F3,				//"F3",
	UI_STRING_MESSAGE_ACCELERATOR_F4,				//"F4",
	UI_STRING_MESSAGE_ACCELERATOR_F5,				//"F5",
	UI_STRING_MESSAGE_ACCELERATOR_F6,				//"F6",
	UI_STRING_MESSAGE_ACCELERATOR_F7,				//"F7",
	UI_STRING_MESSAGE_ACCELERATOR_F8,				//"F8",
	UI_STRING_MESSAGE_ACCELERATOR_F9,				//"F9",
	UI_STRING_MESSAGE_ACCELERATOR_F10,				//"F10",
	UI_STRING_MESSAGE_ACCELERATOR_F11,				//"F11",
	UI_STRING_MESSAGE_ACCELERATOR_F12,				//"F12",
	UI_STRING_MESSAGE_ACCELERATOR_ESC,				//"ESC",
	UI_STRING_MESSAGE_ACCELERATOR_SKILL,			//"SKILL",
	UI_STRING_MESSAGE_ACCELERATOR_INVENTORY,		//"INVENTORY",
	UI_STRING_MESSAGE_ACCELERATOR_GEAR,				//"GEAR",
	UI_STRING_MESSAGE_ACCELERATOR_CHARINFO,			//"CHARINFO",
	UI_STRING_MESSAGE_ACCELERATOR_SKILLINFO,		//"SKILLINFO",
	UI_STRING_MESSAGE_ACCELERATOR_MINIMAP,			//"MINIMAP",
	UI_STRING_MESSAGE_ACCELERATOR_PARTY,			//"PARTY",
	UI_STRING_MESSAGE_ACCELERATOR_MARK,				//"MARK",
	UI_STRING_MESSAGE_ACCELERATOR_HELP,				//"HELP",
	UI_STRING_MESSAGE_ACCELERATOR_QUICKITEM_SLOT,	//"QUICKITEM_SLOT",
	UI_STRING_MESSAGE_ACCELERATOR_EXTEND_CHAT,		//"EXTEND_CHAT",
	UI_STRING_MESSAGE_ACCELERATOR_CHAR,				//"CHAT",
	UI_STRING_MESSAGE_ACCELERATOR_GUILD_CHAT,		//"GUILD_CHAT",
	UI_STRING_MESSAGE_ACCELERATOR_ZONE_CHAT,		//"ZONE_CHAT",
	UI_STRING_MESSAGE_ACCELERATOR_WHISPER,			//"WHISPER",

	// ITEM CLASS NAME

	UI_STRING_MESSAGE_ITEM_CLASS_SWORD,				
	UI_STRING_MESSAGE_ITEM_CLASS_BLADE,				
	UI_STRING_MESSAGE_ITEM_CLASS_CROSS,				
	UI_STRING_MESSAGE_ITEM_CLASS_MACE,				
	UI_STRING_MESSAGE_ITEM_CLASS_MINE,				
	UI_STRING_MESSAGE_ITEM_CLASS_BOMB,				
	UI_STRING_MESSAGE_ITEM_CLASS_MINE_MATERIAL,		
	UI_STRING_MESSAGE_ITEM_CLASS_BOMB_MATERIAL,		
	UI_STRING_MESSAGE_ITEM_CLASS_SG,				
	UI_STRING_MESSAGE_ITEM_CLASS_SMG,				
	UI_STRING_MESSAGE_ITEM_CLASS_AR,				
	UI_STRING_MESSAGE_ITEM_CLASS_SR,				
	UI_STRING_MESSAGE_DESC_CLASS,					
	UI_STRING_MESSAGE_DESC_DURABILITY,				
	UI_STRING_MESSAGE_DESC_SILVERING,				
	UI_STRING_MESSAGE_DESC_DAMAGE,					
	UI_STRING_MESSAGE_DESC_CRITICALHIT,				
	UI_STRING_MESSAGE_DESC_DEFENSE,					
	UI_STRING_MESSAGE_DESC_PROTECTION,				
	UI_STRING_MESSAGE_DESC_ACCURACY,				
	UI_STRING_MESSAGE_DESC_HP,						//HP : "
	UI_STRING_MESSAGE_DESC_MP,						//MP : "
	UI_STRING_MESSAGE_DESC_RANGE,					
	UI_STRING_MESSAGE_DESC_MAGAZINE_NUM,			
	UI_STRING_MESSAGE_DESC_POCKET_NUM,				
	UI_STRING_MESSAGE_DESC_ITEM_NUM,				
	UI_STRING_MESSAGE_DESC_LEFT_NUM,				
	UI_STRING_MESSAGE_DESC_ARRIVAL_LOCATION,		
	UI_STRING_MESSAGE_DESC_NOT_EXIST,				

	UI_STRING_MESSAGE_DESC_NUMBER,						
	UI_STRING_MESSAGE_DESC_MAGAZINE_COUNT,				
	UI_STRING_MESSAGE_DESC_TILE_PIECE,					
	UI_STRING_MESSAGE_DESC_PARTY_NAME,					

	UI_STRING_MESSAGE_DESC_OPTION,						
	UI_STRING_MESSAGE_DESC_REQUIRE,						
	UI_STRING_MESSAGE_DESC_REQUIRE_STAT,					
	UI_STRING_MESSAGE_DESC_ONLY_MALE,					
	UI_STRING_MESSAGE_DESC_ONLY_FEMALE,					
	UI_STRING_MESSAGE_DESC_ONLY_SLAYER,					
	UI_STRING_MESSAGE_DESC_ONLY_VAMPIRE,				
	UI_STRING_MESSAGE_DESC_ALL_STAT_SUM,				
	UI_STRING_MESSAGE_DESC_LEVEL,						
	UI_STRING_MESSAGE_DESC_PRICE,						
	UI_STRING_MESSAGE_DESC_SILVERING_PRICE,				
	UI_STRING_MESSAGE_DESC_CHARGE_PRICE,				
	UI_STRING_MESSAGE_DESC_REPAIR_PRICE,				

	UI_STRING_MESSAGE_CONSUME_HP,						
	UI_STRING_MESSAGE_CONSUME_MP,						

	UI_STRING_MESSAGE_REQUIRE_LEVEL,					
	UI_STRING_MESSAGE_DESC_EXP,							
	UI_STRING_MESSAGE_DESC_LIMIT_LEVEL,					
	UI_STRING_MESSAGE_DESC_CANNOT_LEARN_SKILL,			
	UI_STRING_MESSAGE_DESC_CAN_LEARN_SKILL,				

	UI_STRING_MESSAGE_MOVE,								
	UI_STRING_MESSAGE_CANCEL_MOVE,						
	UI_STRING_MESSAGE_MOVE_F1,							
	UI_STRING_MESSAGE_MOVE_F2,							
	UI_STRING_MESSAGE_MOVE_F3,							
	UI_STRING_MESSAGE_MOVE_F4,							
	UI_STRING_MESSAGE_MOVE_B1,							

	UI_STRING_MESSAGE_DESC_CLICK_EXCHANGE,					
	UI_STRING_MESSAGE_DESC_CANCEL_OK_BUTTON,				
	UI_STRING_MESSAGE_DESC_CANCEL_EXCHANGE,					
	UI_STRING_MESSAGE_DESC_BRING_MONEY,						
	UI_STRING_MESSAGE_DESC_EXCHANGE_MONEY,					
	UI_STRING_MESSAGE_DESC_EXCHANGE_YOUR_MONEY,				

	UI_STRING_MESSAGE_DESC_LEFT_MONEY_AFTER_EXCHANGE,		
	UI_STRING_MESSAGE_DESC_WILL_EXCHANGE_MONEY,				

	UI_STRING_MESSAGE_TRHOW_MONEY_IN_DIALOG,				
	UI_STRING_MESSAGE_SAVE_MONEY_IN_DIALOG,					
	UI_STRING_MESSAGE_BRING_MONEY_IN_DIALOG,				
	UI_STRING_MESSAGE_TRADE_MONEY_IN_DIALOG,				
	UI_STRING_MESSAGE_DIVIDE_MONEY_IN_DIALOG,				
	
	UI_STRING_MESSAGE_BUY_ITEM,							
	UI_STRING_MESSAGE_BUY_ITEM_NUM,						

	UI_STRING_MESSAGE_ASK_DIALOG_BUY_STORAGE,			
	UI_STRING_MESSAGE_ASK_DIALOG_TRADE_OTHER_PLAYER,	
	UI_STRING_MESSAGE_ASK_DIALOG_WAIT_OTHER_PLAYER,		
	UI_STRING_MESSAGE_ASK_DIALOG_CANCEL,				
	UI_STRING_MESSAGE_ASK_DIALOG_REQUEST_JOIN,			
	UI_STRING_MESSAGE_ASK_DIALOG_INVITE,				
	UI_STRING_MESSAGE_CANNOT_FIND_RESULT,				
	UI_STRING_MESSAGE_ENCHANT_CONFIRM,					

	UI_STRING_MESSAGE_DESC_DIALOG_ITEM_CLASS_SG,		
	UI_STRING_MESSAGE_DESC_DIALOG_ITEM_CLASS_SMG,		
	UI_STRING_MESSAGE_DESC_DIALOG_ITEM_CLASS_AR,		
	UI_STRING_MESSAGE_DESC_DIALOG_ITEM_CLASS_SR,		

	UI_STRING_MESSAGE_DESC_DIALOG_DURABILITY,			
	UI_STRING_MESSAGE_DESC_DIALOG_SILVERING,			
	UI_STRING_MESSAGE_DESC_DIALOG_DAMAGE,				
	UI_STRING_MESSAGE_DESC_DIALOG_CRITICALHIT,			
	UI_STRING_MESSAGE_DESC_DIALOG_DEFENSE,				
	UI_STRING_MESSAGE_DESC_DIALOG_PROTECTION,			
	UI_STRING_MESSAGE_DESC_DIALOG_ACCURACY,				
	UI_STRING_MESSAGE_DESC_DIALOG_HP,					//"\tHP : +%d"
	UI_STRING_MESSAGE_DESC_DIALOG_MP,					//"\tMP : +%d"
	UI_STRING_MESSAGE_DESC_DIALOG_RANGE,				
	UI_STRING_MESSAGE_DESC_DIALOG_MAGAZINE_NUM,			
	UI_STRING_MESSAGE_DESC_DIALOG_POCKET_NUM,			
	UI_STRING_MESSAGE_DESC_DIALOG_OPTION,				
	UI_STRING_MESSAGE_DESC_DIALOG_OPTION_EMPTY,			//"\t       %s +%d"
	UI_STRING_MESSAGE_DESC_DIALOG_REQUIRE_EMPTY,		//"\t             ");
	UI_STRING_MESSAGE_DESC_DIALOG_REQUIRE,				
	UI_STRING_MESSAGE_DESC_DIALOG_REQUIRE_STR,			
	UI_STRING_MESSAGE_DESC_DIALOG_REQUIRE_DEX,			
	UI_STRING_MESSAGE_DESC_DIALOG_REQUIRE_INT,			
	UI_STRING_MESSAGE_DESC_DIALOG_REQUIRE_ALL_STAT_SUM,	
	UI_STRING_MESSAGE_DESC_DIALOG_REQUIRE_LEVEL,		
	UI_STRING_MESSAGE_DESC_DIALOG_PRICE,				

	UI_STRING_MESSAGE_FILE_DIALOG_SELECT_PROFILE_PICTURE,	
	UI_STRING_MESSAGE_FILE_DIALOG_SELECT_FILE,				
	UI_STRING_MESSAGE_FILE_DIALOG_SELECT_FILE_OK,			
	UI_STRING_MESSAGE_FILE_DIALOG_CANCEL,					

	UI_STRING_MESSAGE_ENG_DOMAIN_BLADE,					//BLADE
	UI_STRING_MESSAGE_ENG_DOMAIN_SWORD,					//SWORD
	UI_STRING_MESSAGE_ENG_DOMAIN_ENCHANT,				//ENCHANT
	UI_STRING_MESSAGE_ENG_DOMAIN_GUN,					//GUN
	UI_STRING_MESSAGE_ENG_DOMAIN_HEAL,					//HEAL

	UI_STRING_MESSAGE_NOT_SUPPORT_MENU,					
	UI_STRING_MESSAGE_NOT_INPUT_ID_OR_PASSWORD,			
	UI_STRING_MESSAGE_WRONG_SSN,						
	UI_STRING_MESSAGE_INPUT_NAME,						
	UI_STRING_MESSAGE_CANNOT_CONNECT_SERVER,			
	UI_STRING_MESSAGE_SELECT_CHARACTER,					
	UI_STRING_MESSAGE_DELETE_CHARACTER,					
	UI_STRING_MESSAGE_ALL_SLOT_EMPTY,					
	UI_STRING_MESSAGE_NO_MORE_CREATE_CHARACTER,			
	UI_STRING_MESSAGE_FAIL_CREATE_CHARACTER,			
	UI_STRING_MESSAGE_NO_INPUT_NEED_INFO,				
	UI_STRING_MESSAGE_ALREADY_USE_ID,					
	UI_STRING_MESSAGE_CAN_USE_ID,						
	UI_STRING_MESSAGE_RE_INPUT_PASSWORD,				
	


	//Monster Name
	UI_STRING_MESSAGE_MONSTER_NAME_TNDEAD,				
	UI_STRING_MESSAGE_MONSTER_NAME_ARKHAN,				
	UI_STRING_MESSAGE_MONSTER_NAME_ESTROIDER,		
	UI_STRING_MESSAGE_MONSTER_NAME_GOLEMER,				
	UI_STRING_MESSAGE_MONSTER_NAME_DARKSCREAMER,		
	UI_STRING_MESSAGE_MONSTER_NAME_DEADBODY,			
	UI_STRING_MESSAGE_MONSTER_NAME_MODERAS,				
	UI_STRING_MESSAGE_MONSTER_NAME_VANDALIZER,			
	UI_STRING_MESSAGE_MONSTER_NAME_DIRTYSTRIDER,		
	UI_STRING_MESSAGE_MONSTER_NAME_HELLWIZARD,			
	UI_STRING_MESSAGE_MONSTER_NAME_TNSOUL,				
	UI_STRING_MESSAGE_MONSTER_NAME_IRONTEETH,			
	UI_STRING_MESSAGE_MONSTER_NAME_REDEYE,				
	UI_STRING_MESSAGE_MONSTER_NAME_CRIMSONSLAUGTHER,	
	UI_STRING_MESSAGE_MONSTER_NAME_HELLGUARDIAN,		
	UI_STRING_MESSAGE_MONSTER_NAME_SOLDIER,				
	UI_STRING_MESSAGE_MONSTER_NAME_RIPPER,				
	UI_STRING_MESSAGE_MONSTER_NAME_BIGFANG,				
	UI_STRING_MESSAGE_MONSTER_NAME_LORDCHAOS,			
	UI_STRING_MESSAGE_MONSTER_NAME_CHAOSGUARDIAN,		
	UI_STRING_MESSAGE_MONSTER_NAME_HOBBLE,				
	UI_STRING_MESSAGE_MONSTER_NAME_CHAOSNIGHT,			
	UI_STRING_MESSAGE_MONSTER_NAME_WIDOWS,				
	UI_STRING_MESSAGE_MONSTER_NAME_KID,					
	UI_STRING_MESSAGE_MONSTER_NAME_SHADOWWING,			

	//Server Status
	UI_STRING_MESSAGE_SERVER_STATUS_VERY_GOOD,			
	UI_STRING_MESSAGE_SERVER_STATUS_GOOD,				
	UI_STRING_MESSAGE_SERVER_STATUS_NORMAL,				
	UI_STRING_MESSAGE_SERVER_STATUS_BAD,				
	UI_STRING_MESSAGE_SERVER_STATUS_VERY_BAD,			
	UI_STRING_MESSAGE_SERVER_STATUS_DOWN,				
	UI_STRING_MESSAGE_SERVER_STATUS_OPEN,				
	UI_STRING_MESSAGE_SERVER_STATUS_CLOSE,				


	// ItemType
	UI_STRING_MESSAGE_ITEM_TYPE_NORMAL,					
	UI_STRING_MESSAGE_ITEM_TYPE_SPECIAL,				
	UI_STRING_MESSAGE_ITEM_TYPE_MISTERIOUS,				
	
	
	// Storage
	UI_STRING_MESSAGE_STORAGE_FIRST,					
	UI_STRING_MESSAGE_STORAGE_SECOND,					
	UI_STRING_MESSAGE_STORAGE_THIRD,					
	UI_STRING_MESSAGE_BRING_MONEY_FROM_STORAGE,			

	// Char Manager
	UI_STRING_MESSAGE_CHAR_DELETE,						
	UI_STRING_MESSAGE_CHAR_CANCEL,						
	UI_STRING_MESSAGE_CHAR_DELETE_CONFIRM,				
	UI_STRING_MESSAGE_RE_INPUT_CORRECT_SSN,				
	UI_STRING_MESSAGE_CHAR_MANAGER_NAME,					
	UI_STRING_MESSAGE_CHAR_MANAGER_LEVEL,					
	UI_STRING_MESSAGE_CHAR_MANAGER_STR_PURE,				
	UI_STRING_MESSAGE_CHAR_MANAGER_DEX_PURE,				
	UI_STRING_MESSAGE_CHAR_MANAGER_INT_PURE,				
	UI_STRING_MESSAGE_CHAR_MANAGER_SWORD_LEVEL,				
	UI_STRING_MESSAGE_CHAR_MANAGER_BLADE_LEVEL,				
	UI_STRING_MESSAGE_CHAR_MANAGER_GUN_LEVEL,				
	UI_STRING_MESSAGE_CHAR_MANAGER_HEAL_LEVEL,				
	UI_STRING_MESSAGE_CHAR_MANAGER_ENCHANT_LEVEL,			
	UI_STRING_MESSAGE_CHAR_MANAGER_FAME,					
	UI_STRING_MESSAGE_CHAR_MANAGER_CREATEMSG1,				
	UI_STRING_MESSAGE_CHAR_MANAGER_CREATEMSG2,				
	UI_STRING_MESSAGE_CHAR_MANAGER_GRADE,					
	UI_STRING_MESSAGE_CHAR_MANAGER_GRADE_EXP,				


	// Option Menu
	UI_STRING_MESSAGE_OPTION_MENU_ENTER_CHATTING,			
	UI_STRING_MESSAGE_OPTION_MENU_NORMAL_CHATTING,			
	UI_STRING_MESSAGE_OPTION_MENU_3D_ACCEL,					
	UI_STRING_MESSAGE_OPTION_MENU_ALPHA_HPBAR,				
	UI_STRING_MESSAGE_OPTION_MENU_SHED_BLOOD,				
	UI_STRING_MESSAGE_OPTION_MENU_HIDE_SOFT,				
	UI_STRING_MESSAGE_OPTION_MENU_GAME_BRIGHT,				
	UI_STRING_MESSAGE_OPTION_MENU_CHATTING_TALK,			
	UI_STRING_MESSAGE_OPTION_MENU_PUT_FPS,					
	UI_STRING_MESSAGE_OPTION_MENU_WINDOW_ALPHA,				
	UI_STRING_MESSAGE_OPTION_MENU_DENSITY_ALPHA,			
	UI_STRING_MESSAGE_OPTION_MENU_SOUND_VOLUME,				
	UI_STRING_MESSAGE_OPTION_MENU_MUSIC_VOLUME,				
	UI_STRING_MESSAGE_OPTION_MENU_SHOW_BASIC_HELP,			
	UI_STRING_MESSAGE_OPTION_MENU_NO_LISTEN_BAD_TALK,		
	UI_STRING_MESSAGE_OPTION_MENU_LOAD_ALL_IMAGE,			
	UI_STRING_MESSAGE_OPTION_MENU_CHATTING_COLOR_WHITE,		
	UI_STRING_MESSAGE_OPTION_MENU_RUN_TEEN_VERSION,			
	UI_STRING_MESSAGE_OPTION_MENU_OPEN_WINDOW_WHEN_WHISPER,	
	UI_STRING_MESSAGE_OPTION_MENU_ACCEL_NAME,				
	UI_STRING_MESSAGE_OPTION_MENU_ACCEL_KEY,				
	UI_STRING_MESSAGE_OPTION_MENU_MSG1,						
	UI_STRING_MESSAGE_OPTION_MENU_MSG2,						
	UI_STRING_MESSAGE_OPTION_NOT_SEND_MY_INFO,				

	// Grade
	UI_STRING_MESSAGE_GRADE_PIVATE,								
	UI_STRING_MESSAGE_GRADE_SERENT,								
	UI_STRING_MESSAGE_GRADE_FEACEL,								
	UI_STRING_MESSAGE_GRADE_LITENA,								
	UI_STRING_MESSAGE_GRADE_KAINEL,								
	UI_STRING_MESSAGE_GRADE_GENEAL,								
	UI_STRING_MESSAGE_GRADE_FORE_GENEAL,						
	UI_STRING_MESSAGE_GRADE_MAJORIS_GENEAL,						
	UI_STRING_MESSAGE_GRADE_CLOEL_GENEAL,						
	UI_STRING_MESSAGE_GRADE_MARSHAL ,							

	UI_STRING_MESSAGE_GRADE_RITTER,								
	UI_STRING_MESSAGE_GRADE_REICHSRITTER,						
	UI_STRING_MESSAGE_GRADE_BARONET,							
	UI_STRING_MESSAGE_GRADE_PREYHER,							
	UI_STRING_MESSAGE_GRADE_GRAF,								
	UI_STRING_MESSAGE_GRADE_MARKGRAF,							
	UI_STRING_MESSAGE_GRADE_PFALZGRAF,							
	UI_STRING_MESSAGE_GRADE_FURST,								
	UI_STRING_MESSAGE_GRADE_HERZOG,								
	UI_STRING_MESSAGE_GRADE_LANDESHER,							



	// Client Info
	UI_STRING_MESSAGE_CLIENT_VERSION,							//Version
	UI_STRING_MESSAGE_NETMARBLE_CLIENT_VERSION,

	UI_STRING_MESSAGE_OTHER_INFO_STR_PURE,						
	UI_STRING_MESSAGE_OTHER_INFO_DEX_PURE,						
	UI_STRING_MESSAGE_OTHER_INFO_INT_PURE,						

	UI_STRING_MESSAGE_OTHER_INFO_STR_CUR,						
	UI_STRING_MESSAGE_OTHER_INFO_DEX_CUR,						
	UI_STRING_MESSAGE_OTHER_INFO_INT_CUR,						
	UI_STRING_MESSAGE_OTHER_INFO_FAME,							
	UI_STRING_MESSAGE_OTHER_INFO_TEAM_NAME,						
	UI_STRING_MESSAGE_OTHER_INFO_CLAN_NAME,						

	UI_STRING_MESSAGE_TIP_CHANGE_PICTURE_CLICK_HERE,			

	STRING_MESSAGE_UP_TO_GRADE,									
	UI_STRING_MESSAGE_GRADE_NAME,								
	UI_STRING_MESSAGE_GRADE_LEVEL,								

	UI_STRING_MESSAGE_ENG_DOMAIN_BLADE2,						//"BLADE";
	UI_STRING_MESSAGE_ENG_DOMAIN_SWORD2,						//"SWORD";
	UI_STRING_MESSAGE_ENG_DOMAIN_ENCHANT2,						//"ENCHANT";
	UI_STRING_MESSAGE_ENG_DOMAIN_GUN2,							//"GUN";
	UI_STRING_MESSAGE_ENG_DOMAIN_HEAL2,							//"HEAL";

	UI_STRING_MESSAGE_DESC_CLASS2,								
	STRING_MESSAGE_ITEM_TO_ITEM_FAIL_NO_PREMIUM_SLAYER,			
	STRING_MESSAGE_ITEM_TO_ITEM_FAIL_NO_PREMIUM_VAMPIRE,		

	STRING_MESSAGE_DISMISS_AFTER_SECOND,							
	UI_STRING_MESSAGE_MODIFY_INFO,							
	
	UI_STRING_MESSAGE_START_TRACE,								
	UI_STRING_MESSAGE_CANCEL_TRACE,								
	UI_STRING_MESSAGE_TRACE,									
	UI_STRING_MESSAGE_CANNOT_TRACE,								

	UI_STRING_MESSAGE_OPTION_DO_NOT_WAR_MSG,					
	UI_STRING_MESSAGE_OPTION_DO_NOT_LAIR_MSG,					

	UI_STRING_MESSAGE_SHOW_GRADE1_INFO_WINDOW,					
	UI_STRING_MESSAGE_SHOW_GRADE2_INFO_WINDOW,					

	UI_STRING_MESSAGE_INCREASE_CRITICAL_10,						
	UI_STRING_MESSAGE_INCREASE_DEFENSE_5,						
	UI_STRING_MESSAGE_INCREASE_TOHIT_5,							
	UI_STRING_MESSAGE_INCREASE_HP_10,							
	UI_STRING_MESSAGE_INCREASE_MP_15,							
	UI_STRING_MESSAGE_INCREASE_DAMAGE_3,						
	UI_STRING_MESSAGE_INCREASE_ATTACKSPEED_15,					
	UI_STRING_MESSAGE_INCREASE_HP_20,							
	UI_STRING_MESSAGE_INCREASE_DEFENSE_10,						
	UI_STRING_MESSAGE_INCREASE_PROTECTION_10,					
	UI_STRING_MESSAGE_DECREASE_HP_EXHAUSTION_10_PERCENT,		
	UI_STRING_MESSAGE_INCREASE_ENCHANT_DAMAGE_10_PERCENT,		
	UI_STRING_MESSAGE_INCREASE_HEAL_DAMAGE_10_PERCENT,			
	UI_STRING_MESSAGE_INCREASE_NEAR_ATTACK_DAMAGE_10_PERCENT,	
	UI_STRING_MESSAGE_INCREASE_HP_RESTORE_SPEED_15_PERCENT,		
	UI_STRING_MESSAGE_INCREASE_RESISTANCE_ACID_15_PERCENT,		
	UI_STRING_MESSAGE_INCREASE_RESISTANCE_BLOODY_15_PERCENT,	
	UI_STRING_MESSAGE_INCREASE_RESISTANCE_CURSE_15_PERCENT,		
	UI_STRING_MESSAGE_INCREASE_RESISTANCE_POISON_15_PERCENT,	
	UI_STRING_MESSAGE_INCREASE_DAMAGE_STORM_20_PERCENT,			
	UI_STRING_MESSAGE_INCREASE_RANGE_STORM_5_BY_5,				
	UI_STRING_MESSAGE_INCREASE_SUCCESS_RATIO_POISON_10_PERCENT,	
	UI_STRING_MESSAGE_INCREASE_SUCCESS_RATIO_ACID_10_PERCENT,	
	UI_STRING_MESSAGE_INCREASE_SUCCESS_RATIO_CURSE_10_PERCENT,	
	UI_STRING_MESSAGE_INCREASE_SUCCESS_RATIO_BLOODY_10_PERCENT,	
	UI_STRING_MESSAGE_INCREASE_SUCCESS_RATIO_INNATE_10_PERCENT,	
	UI_STRING_MESSAGE_INCREASE_SUCCESS_RATIO_SUMMON_10_PERCENT,	
	UI_STRING_MESSAGE_DECREASE_MP_EXHAUSTION_10_PERCENT,		
	UI_STRING_MESSAGE_INCREASE_HP_STEAL_2_PERCENT,				
	UI_STRING_MESSAGE_INCREASE_MP_STEAL_2_PERCENT,				
	UI_STRING_MESSAGE_INCREASE_LUCKY_2,							
	UI_STRING_MESSAGE_INCREASE_KEEP_TIME_ACID_SWAMP_20_PERCENT,	
	UI_STRING_MESSAGE_INCREASE_KEEP_TIME_PARALYZE_20_PERCENT,	
	UI_STRING_MESSAGE_INCREASE_KEEP_TIME_DARKNESS_30_PERCENT,	
	UI_STRING_MESSAGE_INCREASE_RANGE_DARKNESS_5_BY_5,			
	UI_STRING_MESSAGE_CANNOT_UP_GRADE,							

	STRING_MESSAGE_SELECT_PC_CANNOT_PLAY,						
	STRING_MESSAGE_SELECT_PC_NOT_BILLING_CHECK,					
	STRING_MESSAGE_SELECT_PC_CANNOT_PLAY_BY_ATTR,				

	UI_STRING_MESSAGE_NEVER_CANNOT_LEARN_SKILL,					
	UI_STRING_MESSAGE_ALREADY_LEARNED_SKILL,					
	UI_STRING_MESSAGE_CANNOT_LEARN_SKILL_YET,					
	UI_STRING_MESSAGE_CAN_LEARN_SKILL_NOW,						
	UI_STRING_MESSAGE_ACCELERATOR_GRADE1,
	UI_STRING_MESSAGE_ACCELERATOR_GRADE2,
	UI_STRING_MESSAGE_LEARN_GRADE_SKILL_CONFIRM,				

	UI_STRING_MESSAGE_TREE_OK,									
	UI_STRING_MESSAGE_TREE_CANCEL,								

    STRING_MESSAGE_TRADE_GIFT_BOX_OK,             
    STRING_MESSAGE_TRADE_GIFT_BOX_NO_ITEM,        
    STRING_MESSAGE_TRADE_GIFT_BOX_ALREADY_TRADE,  

	STRING_MESSAGE_XMAS_TREE_CANNOT_USE,			
	STRING_MESSAGE_XMAS_CARD_CANNOT_USE,			
	STRING_MESSAGE_NOT_USE_SAFETY_POSITION,			
	STRING_MESSAGE_NOT_USE_SAFETY_ZONE,				

	UI_STRING_MESSAGE_ENCHANT_CONFIRM_2,					

	UI_STRING_MESSAGE_DEPOSIT_LIMIT,				
	UI_STRING_MESSAGE_WITHDRAW_LIMIT,				

	// 2003.1.14
	STRING_MESSAGE_EVENT_PREMIUM_HALF_SLAYER,		
	STRING_MESSAGE_EVENT_PREMIUM_HALF_VAMPIRE,		
	STRING_MESSAGE_EVENT_PREMIUM_HALF_SLAYER_END,	
	STRING_MESSAGE_EVENT_PREMIUM_HALF_VAMPIRE_END,	

	STRING_MESSAGE_REWARD_OK,						
	STRING_MESSAGE_REWARD_FAIL,						
    STRING_MESSAGE_NO_EMPTY_SLOT,					

	UI_STRING_MESSAGE_OPTION_DO_NOT_HOLY_LAND_MSG,	
	UI_STRING_MESSAGE_HOLY_LAND_TOTAL_FEE,			
	UI_STRING_MESSAGE_HOLY_LAND_CAN_BRING_FEE,		
	UI_STRING_MESSAGE_HOLY_LAND_TOTAL_FEE_DESC,		
	UI_STRING_MESSAGE_HOLY_LAND_INPUT_BRING_FEE,	
	UI_STRING_MESSAGE_HOLY_LAND_CLICK_INPUT_FEE,	
	UI_STRING_MESSAGE_HOLY_LAND_OK,					
	
	STRING_MESSAGE_NO_TEAM,							
	STRING_MESSAGE_NO_CLAN,							
	STRING_MESSAGE_NOT_TEAM_MASTER,					
	STRING_MESSAGE_NOT_CLAN_MASTER,					
	STRING_MESSAGE_TEAM_HAS_NO_CASTLE,				
	STRING_MESSAGE_CLAN_HAS_NO_CASTLE,				
	STRING_MESSAGE_TEAM_NOT_YOUR_CASTLE,			
	STRING_MESSAGE_CLAN_NOT_YOUR_CASTLE,			

	STRING_MESSAGE_SUCCESS_BRING_FEE,				
	STRING_MESSAGE_FAIL_BRING_FEE,					
	
	UI_STRING_MESSAGE_BRING_FEE_MSG,				

	UI_STRING_MESSAGE_BRING_FEE_LIMIT,				
	UI_STRING_MESSAGE_RACE_WAR,						
	
	STRING_MESSAGE_WAR_SCHEDULE_FULL,						
	STRING_MESSAGE_WAR_ALREADY_REGISTERED,					
	STRING_MESSAGE_WAR_NOT_ENOUGH_MONEY,					
	STRING_MESSAGE_WAR_REGISTRATION_OK,						

	STRING_MESSAGE_CANNOT_MOVE_SAFETY_ZONE_BLOOD_BIBLE,		
	STRING_MESSAGE_ALREADY_HAS_CASTLE,						
	STRING_MESSAGE_WAR_UNAVAILABLE,							

	UI_STRING_MESSAGE_STATUS_TIME_FORMAT,					
	UI_STRING_MESSAGE_STATUS_LEFT_TIME,						
	UI_STRING_MESSAGE_GUILD_WAR,							

	STRING_MESSAGE_BLOOD_BIBLE_BONUS_ARMEGA,				
	STRING_MESSAGE_BLOOD_BIBLE_BONUS_MIHOLE,				
	STRING_MESSAGE_BLOOD_BIBLE_BONUS_KIRO,					// INT+5, DEX +5  
	STRING_MESSAGE_BLOOD_BIBLE_BONUS_INI,					
	STRING_MESSAGE_BLOOD_BIBLE_BONUS_GREGORI,				
	STRING_MESSAGE_BLOOD_BIBLE_BONUS_CONCILIA,				// HP +50  
	STRING_MESSAGE_BLOOD_BIBLE_BONUS_LEGIOS,				
	STRING_MESSAGE_BLOOD_BIBLE_BONUS_HILLEL,				
	STRING_MESSAGE_BLOOD_BIBLE_BONUS_JAVE,					
	STRING_MESSAGE_BLOOD_BIBLE_BONUS_NEMA,					
	STRING_MESSAGE_BLOOD_BIBLE_BONUS_AROSA,					
	STRING_MESSAGE_BLOOD_BIBLE_BONUS_CHASPA,				// STR +5, INT +5


	UI_STRING_MESSAGE_BLOOD_BIBLE_ARMEGA,				
	UI_STRING_MESSAGE_BLOOD_BIBLE_MIHOLE,				
	UI_STRING_MESSAGE_BLOOD_BIBLE_KIRO,					
	UI_STRING_MESSAGE_BLOOD_BIBLE_INI,					
	UI_STRING_MESSAGE_BLOOD_BIBLE_GREGORI,				
	UI_STRING_MESSAGE_BLOOD_BIBLE_CONCILIA,				
	UI_STRING_MESSAGE_BLOOD_BIBLE_LEGIOS,				
	UI_STRING_MESSAGE_BLOOD_BIBLE_HILLEL,				
	UI_STRING_MESSAGE_BLOOD_BIBLE_JAVE,					
	UI_STRING_MESSAGE_BLOOD_BIBLE_NEMA,					
	UI_STRING_MESSAGE_BLOOD_BIBLE_AROSA,				
	UI_STRING_MESSAGE_BLOOD_BIBLE_CHASPA,				


	UI_STRING_MESSAGE_BLOOD_BIBLE_ARMEGA_ENG,				// ARMEGA
	UI_STRING_MESSAGE_BLOOD_BIBLE_MIHOLE_ENG,				// MIHOLE
	UI_STRING_MESSAGE_BLOOD_BIBLE_KIRO_ENG,					// KIRO
	UI_STRING_MESSAGE_BLOOD_BIBLE_INI_ENG,					// INI
	UI_STRING_MESSAGE_BLOOD_BIBLE_GREGORI_ENG,				// GREGORI
	UI_STRING_MESSAGE_BLOOD_BIBLE_CONCILIA_ENG,				// CONCILIA
	UI_STRING_MESSAGE_BLOOD_BIBLE_LEGIOS_ENG,				// LEGIOS
	UI_STRING_MESSAGE_BLOOD_BIBLE_HILLEL_ENG,				// HILLEL
	UI_STRING_MESSAGE_BLOOD_BIBLE_JAVE_ENG,					// JAVE
	UI_STRING_MESSAGE_BLOOD_BIBLE_NEMA_ENG,					// NEMA
	UI_STRING_MESSAGE_BLOOD_BIBLE_AROSA_ENG,				// AROSA
	UI_STRING_MESSAGE_BLOOD_BIBLE_CHASPA_ENG,				// CHASPA

	UI_STRING_MESSAGE_BLOOD_BIBLE_STATUS_DROP,				
	UI_STRING_MESSAGE_BLOOD_BIBLE_STATUS_HAS_SLAYER,		
	UI_STRING_MESSAGE_BLOOD_BIBLE_STATUS_HAS_VAMPIRE,		
	UI_STRING_MESSAGE_BLOOD_BIBLE_STATUS_NONE,				
	UI_STRING_MESSAGE_BLOOD_BIBLE_STATUS_SLAYER,			
	UI_STRING_MESSAGE_BLOOD_BIBLE_STATUS_VAMPIRE,			
	
	UI_STRING_MESSAGE_BLOOD_BIBLE_DESC_POSITION,			
	UI_STRING_MESSAGE_BLOOD_BIBLE_DESC_STATUS,				
	UI_STRING_MESSAGE_BLOOD_BIBLE_DESC_PLAYER,				

	UI_STRING_MESSAGE_BLOOD_BIBLE_STATUS_ATTACK_GUILD,		
	UI_STRING_MESSAGE_BLOOD_BIBLE_STATUS_DEFENSE_GUILD,		
	
	STRING_MESSAGE_RACE_WAR_JOIN_FAILED,					
	STRING_MESSAGE_RACE_WAR_JOIN_OK,						

	UI_STRING_MESSAGE_BLOOD_BIBLE_DESC_SHRINE_RACE,			

	STRING_MESSAGE_SLAYER,									
	STRING_MESSAGE_VAMPIRE,									

	STRING_MESSAGE_RACE_WAR_GO_FIRST_SERVER,				

	STRING_MESSAGE_GIVE_EVENT_ITEM_FAIL_NOW,				
	STRING_MESSAGE_GIVE_EVENT_ITEM_FAIL,					
	STRING_MESSAGE_GIVE_EVENT_ITEM_OK,						
	STRING_MESSAGE_GIVE_PREMIUM_USER_ONLY,					

	STRING_MESSAGE_COUPLE_MEET_SUCCESS,						
	STRING_MESSAGE_COUPLE_CANNOT_MEET,						
	STRING_MESSAGE_MEET_WAIT_TIME_EXPIRED,					

	STRING_MESSAGE_COUPLE_APART_SUCCESS,					
	STRING_MESSAGE_NOT_COUPLE,								
	STRING_MESSAGE_APART_WAIT_TIME_EXPIRED,					

	UI_STRING_MESSAGE_HOPE_COUPLE_MSG,						
	UI_STRING_MESSAGE_BREAK_UP_COUPLE_MSG,					
	UI_STRING_MESSAGE_COMPLETE,						
	UI_STRING_MESSAGE_OTHER_PLAYER_NAME,					

	UI_STRING_MESSAGE_FORCE_BREAK_UP_COUPLE,				

	STRING_MESSAGE_COUPLE,									
	STRING_MESSAGE_MOVE_DELAY_SEC,							
	STRING_MESSAGE_COUPLE_MOVE_START,						
	STRING_MESSAGE_COUPLE_CAN_NOT_FIND,						

	STRING_MESSAGE_COUPLE_NOT_EVENT_TERM,			
	STRING_MESSAGE_COUPLE_ALREADY_WAITING,				
	STRING_MESSAGE_COUPLE_LOGOFF,						
	STRING_MESSAGE_COUPLE_DIFFERENT_RACE,				
	STRING_MESSAGE_COUPLE_SAME_SEX,					
	STRING_MESSAGE_COUPLE_NOT_PAY_PLAYER,				
	STRING_MESSAGE_COUPLE_ALREADY_COUPLE,				
	STRING_MESSAGE_COUPLE_WAS_COUPLE,					
	STRING_MESSAGE_COUPLE_NOT_ENOUGH_GOLD,				
	STRING_MESSAGE_COUPLE_NOT_ENOUGH_ATTR,				
	STRING_MESSAGE_COUPLE_NOT_ENOUGH_LEVEL,			
	STRING_MESSAGE_COUPLE_INVENTORY_FULL,				
	STRING_MESSAGE_COUPLE_NO_WAITING,					
	STRING_MESSAGE_COUPLE_NOT_COUPLE,					

	UI_STRING_MESSAGE_LOVE_CHAIN,						
	UI_STRING_MESSAGE_WILL_YOU_GO_BILING_PAGE,			
	UI_STRING_MESSAGE_GO_BILING_PAGE,					
	STRING_MESSAGE_LOGOUT_BY_PAYTIME,					
	STRING_MESSAGE_LOGOUT_BY_FREEPLAY_LEVEL,			
	STRING_MESSAGE_LOGOUT_BY_LEVEL,						
	
	UI_STRING_MESSAGE_CANNOT_UP_LEVEL_BY_FAME,			
	UI_STRING_MESSAGE_NEED_FAME,						

	
	UI_STRING_MESSAGE_QUEST_HAN,						
	UI_STRING_MESSAGE_QUEST_ENG,						// Quest
	UI_STRING_MESSAGE_DAY,								
	UI_STRING_MESSAGE_HOUR,								
	UI_STRING_MESSAGE_MINUTE,							
	UI_STRING_MESSAGE_SECOND,							
	UI_STRING_MESSAGE_LEFT_TIME,						
	UI_STRING_MESSAGE_EXPIRED_ITEM,						
	
	UI_STRING_MESSAGE_SELECT_QUEST_SLAYER,				
	UI_STRING_MESSAGE_SELECT_QUEST_VAMPIRE,				
	UI_STRING_MESSAGE_CANCEL_SELECT_QUEST,				
	UI_STRING_MESSAGE_CANCEL_LEARN_SKILL,				
	UI_STRING_MESSAGE_NUMBER_OF_ANIMALS,				

	UI_STRING_MESSAGE_EXPIRED_TIME_MONSTER_KILL_QUEST,			
	UI_STRING_MESSAGE_FINISH_MONSTER_KILL_QUEST,				
	UI_STRING_MESSAGE_CAN_REQUITAL_FROM_NPC,					
	UI_STRING_MESSAGE_START_MONSTER_KILL_QUEST,					
	UI_STRING_MESSAGE_FAIL_ALREADY_START_MONSTER_KILL_QUEST,	
	UI_STRING_MESSAGE_FAIL_MONSTER_KILL_QUEST_BY_STATUS,		
	UI_STRING_MESSAGE_SUCCESS_MONSTER_KILL_QUEST,				
	UI_STRING_MESSAGE_NOT_YET_COMPLETE_MONSTER_KILL_QUEST,		
	UI_STRING_MESSAGE_INVENTORY_FULL_MONSTER_KILL_QUEST,		
	UI_STRING_MESSAGE_NOT_IN_QUEST,								
	UI_STRING_MESSAGE_FAIL_QUEST_EXPIRED_TIME,					
	UI_STRING_MESSAGE_TIME_LIMIT,								
	UI_STRING_MESSAGE_CANNOT_APPLY_QUEST,						
	
	UI_STRING_MESSAGE_COMPLETE_QUEST,
	UI_STRING_MESSAGE_FAIL_TIME_OVER_QUEST,
	UI_STRING_MESSAGE_MEET_NPC,
	
	UI_STRING_MESSAGE_FAIL_INVALID_NPC,
	UI_STRING_MESSAGE_FAIL_BUG,
	
	UI_STRING_MESSAGE_GATHER_ITEM,								
	STRING_MESSAGE_MONSTER_KILL_QUEST_STRING_SET,				
	STRING_MESSAGE_MONSTER_KILL_QUEST_STRING_SET_VAMPIRE,		
	STRING_MESSAGE_CANCEL_MONSTER_KILL_QUEST,					
	STRING_MESSAGE_YES_I_SEE,									

	
	UI_STRING_MESSAGE_QUEST_MONSTER_KILL,						
	UI_STRING_MESSAGE_QUEST_MEET_NPC,							
	UI_STRING_MESSAGE_QUEST_GATHER_ITEM,						
	
	UI_STRING_MESSAGE_QUEST_DESCRIPTION_TIME_TOTAL,				
	UI_STRING_MESSAGE_QUEST_DESCRIPTION_TIME_ELAPSE,			
	UI_STRING_MESSAGE_QUEST_DESCRIPTION_TIME_REMAIN,			
	UI_STRING_MESSAGE_QUEST_DESCRIPTION_TIME_NO_REMAIN,			
	UI_STRING_MESSAGE_FAIL_QUEST,								
	UI_STRING_MESSAGE_SELECT_EVENT_GIFT,						
	UI_STRING_MESSAGE_PLEASE_SCRATCH_IMAGE,						
	UI_STRING_MESSAGE_WIN_A_PRIZE_SAME_IMAGE,					
	UI_STRING_MESSAGE_CONGRATULATIONS,							
	UI_STRING_MESSAGE_WIN_A_PRIZE,								

	STRING_MESSAGE_MEET_NPC_SLAYER,								
	STRING_MESSAGE_MEET_NPC_VAMPIRE,							

	STRING_MESSAGE_CANCEL_QUEST_VAMPIRE,						

	UI_STRING_MESSAGE_FAIL_LOTTERY,
	UI_STRING_MESSAGE_WIN_A_PRIZE2,								
	UI_STRING_MESSAGE_USER_1,									

	STRING_MESSAGE_RIPATY_SCRIPT_1,
	STRING_MESSAGE_RIPATY_SCRIPT_2,
	STRING_MESSAGE_RIPATY_SCRIPT_3,
	STRING_MESSAGE_RIPATY_SCRIPT_4,
	STRING_MESSAGE_RIPATY_SCRIPT_5,
	STRING_MESSAGE_RIPATY_SCRIPT_6,
	STRING_MESSAGE_RIPATY_SCRIPT_7,
	STRING_MESSAGE_RIPATY_SCRIPT_8,
	STRING_MESSAGE_RIPATY_SCRIPT_9,

	STRING_MESSAGE_AMATA_SCRIPT_1,
	STRING_MESSAGE_AMATA_SCRIPT_2,
	STRING_MESSAGE_AMATA_SCRIPT_3,
	STRING_MESSAGE_AMATA_SCRIPT_4,
	STRING_MESSAGE_AMATA_SCRIPT_5,
	STRING_MESSAGE_AMATA_SCRIPT_6,
	STRING_MESSAGE_AMATA_SCRIPT_7,
	STRING_MESSAGE_AMATA_SCRIPT_8,
	STRING_MESSAGE_AMATA_SCRIPT_9,
	
	UI_STRING_MESSAGE_QUEST_NAME_FIND_ANCIENT_DOCUMENT,					
	UI_STRING_MESSAGE_QUEST_NAME_FIND_ANCIENT_MAP,						
	UI_STRING_MESSAGE_QUEST_NAME_FIND_SOUL_STONE,						

	UI_STRING_MESSAGE_NOT_IN_QUEST2,							
//	UI_STRING_MESSAGE_EVENT_QUEST_2,
//	UI_STRING_MESSAGE_EVENT_QUEST_3,
//	UI_STRING_MESSAGE_EVENT_QUEST_4,
//	UI_STRING_MESSAGE_EVENT_QUEST_5,
	
	UI_STRING_MESSAGE_TAKE_OUT_OK,							
	UI_STRING_MESSAGE_TAKE_OUT_FAIL,						
	STRING_MESSAGE_CANNOT_TAKE_OUT_ITEM_FROM_SHOP,			
	UI_STRING_MESSAGE_CONFIRM_SELECT_ITEM_FROM_SHOP,		
	UI_STRING_MESSAGE_ITEM_SHOP,							

	STRING_MESSAGE_CLEAR_RANK_BONUS_OK,           
    STRING_MESSAGE_NO_RANK_BONUS,                 
    STRING_MESSAGE_ALREADY_CLEAR_RANK_BONUS,      

	UI_STRING_MESSAGE_BULLETIN_BOARD_OK,					
	UI_STRING_MESSAGE_BULLETIN_BOARD_CANCEL,				

	STRING_MESSAGE_BULLETIN_BOARD_CANNOT_USE,				
	UI_STRING_MESSAGE_CAN_TRANS,
	
	UI_STRING_MESSAGE_TRANS_ITEM,
	UI_STRING_MESSAGE_RESURRECT_BY_ELIXIR,
	UI_STRING_MESSAGE_RESURRECT_BY_SCROLL,
	UI_STRING_CANNOT_USE,

	UI_STRING_MESSAGE_MIXING_FORGE_OK,							
	UI_STRING_MESSAGE_MIXING_FORGE_CANCEL,						

	UI_STRING_MESSAGE_COMPLETE_MERGE_ITEM,						
	UI_STRING_MESSAGE_FAIL_MERGE_ITEM,							
	STRING_MESSAGE_USE_GUILD_MEMBER_ONLY,						
	STRING_MESSAGE_CANNOT_USE_RIDE_MOTORCYCLE,					
	UI_STRING_MESSAGE_CANNOT_MIXING_SPECIAL_ITEM,				

	UI_STRING_MESSAGE_CANNOT_MIXING_OPTION_COUNT,				
	UI_STRING_MESSAGE_CANNOT_MIXING_ITEM_CLASS,					
	UI_STRING_MESSAGE_CANNOT_MIXING_ITEM_TYPE,					
	UI_STRING_MESSAGE_CANNOT_MIXING_ITEM_OPTION,				
	
	UI_STRING_MESSAGE_WHAT_OPTION_REMOVE,						
	UI_STRING_MESSAGE_CONFIRM_REMOVE_OPTION,					
	UI_STRING_MESSAGE_CAN_REMOVE_OPTION,						
	UI_STRING_MESSGAE_CANNOT_REMOVE_OPTION,						

	UI_STRING_MESSAGE_SELECT_OPTION,							
	UI_STRING_MESSAGE_QUESTION_REMOVE_OPTION,					
	STRING_MESSAGE_FAILED_REMOVE_OPTION,						
	STRING_MESSAGE_SUCCESS_REMOVE_OPTION,						

	UI_STRING_MESSAGE_DESC_OTHER_TRIBE,					
	UI_STRING_MESSAGE_CONSUME_EP,						

	UI_STRING_MESSAGE_EQUIP_OUSTERS_CIRCLET,			
	UI_STRING_MESSAGE_EQUIP_OUSTERS_COAT,				
	UI_STRING_MESSAGE_EQUIP_OUSTERS_WEAPON,				
	UI_STRING_MESSAGE_EQUIP_OUSTERS_BOOTS,				
	UI_STRING_MESSAGE_EQUIP_OUSTERS_ARMSBAND,			
	UI_STRING_MESSAGE_EQUIP_OUSTERS_RING,				
	UI_STRING_MESSAGE_EQUIP_OUSTERS_PENDENT,			
	UI_STRING_MESSAGE_EQUIP_OUSTERS_STONE,				

	UI_STRING_MESSAGE_OUSTERS_STONE,				
	
	UI_STRING_MESSAGE_GRADE_MALCHUT,					
	UI_STRING_MESSAGE_GRADE_YESOD,						
	UI_STRING_MESSAGE_GRADE_HOD,						
	UI_STRING_MESSAGE_GRADE_NETRETH,					
	UI_STRING_MESSAGE_GRADE_TIPHRETH,					
	UI_STRING_MESSAGE_GRADE_GEBURAH,					
	UI_STRING_MESSAGE_GRADE_CHESED,						
	UI_STRING_MESSAGE_GRADE_BINAH,						
	UI_STRING_MESSAGE_GRADE_CHOKMA,						
	UI_STRING_MESSAGE_GRADE_KEATHER,					

	UI_STRING_MESSAGE_SKILL_LEVEL,						// Skill Level : %d
	UI_STRING_MESSAGE_REQUIRE_ELEMENTAL_LEVEL,			
	UI_STRING_MESSAGE_LEARN_SKILL,						
	UI_STRING_MESSAGE_LEARN_SKILL2,						
	UI_STRING_MESSAGE_SKILL_LEVEL_UP,					
	UI_STRING_MESSAGE_REQUIRE_SKILL_POINT,				

	UI_STRING_MESSAGE_ELEMENTAL_FIRE,					
	UI_STRING_MESSAGE_ELEMENTAL_WATER,					
	UI_STRING_MESSAGE_ELEMENTAL_EARTH,					
	UI_STRING_MESSAGE_ELEMENTAL_WIND,					
	UI_STRING_MESSAGE_ELEMENTAL_SUM,					
	
	UI_STRING_MESSAGE_EP,								

	UI_STRING_MESSAGE_NOT_SHOW_GUILD_CHATTING,				
	UI_STRING_MESSAGE_SHOW_GUILD_CHATTING,					
	UI_STRING_MESSAGE_GUILD_CHATTING,						
	
	UI_STRING_MESSAGE_RANK_BONUS_WOOD_SKIN,					
    UI_STRING_MESSAGE_RANK_BONUS_WIND_SENSE,				
    UI_STRING_MESSAGE_RANK_BONUS_HOMING_EYE,				
	UI_STRING_MESSAGE_RANK_BONUS_LIFE_ENERGY,				
	UI_STRING_MESSAGE_RANK_BONUS_SOUL_ENERGY,				
	UI_STRING_MESSAGE_RANK_BONUS_STONE_MAUL,				
	UI_STRING_MESSAGE_RANK_BONUS_SWIFT_ARM,					
	UI_STRING_MESSAGE_RANK_BONUS_FIRE_ENDOW,				
	UI_STRING_MESSAGE_RANK_BONUS_WATER_ENDOW,				
	UI_STRING_MESSAGE_RANK_BONUS_EARTH_ENDOW,				
	UI_STRING_MESSAGE_RANK_BONUS_ANTI_ACID_SKIN,			
	UI_STRING_MESSAGE_RANK_BONUS_ANTI_BLOODY_SKIN,			
	UI_STRING_MESSAGE_RANK_BONUS_ANTI_CURSE_SKIN,			
	UI_STRING_MESSAGE_RANK_BONUS_ANTI_POISON_SKIN,			
	UI_STRING_MESSAGE_RANK_BONUS_ANTI_SILVER_DAMAGE_SKIN,	
	UI_STRING_MESSAGE_RANK_BONUS_BLESS_OF_NATURE,			
	UI_STRING_MESSAGE_RANK_BONUS_LIFE_ABSORB,				
	UI_STRING_MESSAGE_RANK_BONUS_SOUL_ABSORB,				
	UI_STRING_MESSAGE_RANK_BONUS_MYSTIC_RULE,				

	UI_STRING_MESSAGE_HPBAR_EP_DESCRIPTION,					// "EP:%d/%d"

	UI_STRING_MESSAGE_LEFT_BONUS_POINT,						

	UI_STRING_MESSAGE_GUILD,								
	UI_STRING_MESSAGE_GUILD_INFO,							
	UI_STRING_MESSAGE_GUILD_MEMBER_LIST,					
	UI_STRING_MESSAGE_GUILD_HELP,							
	
	UI_STRING_MESSAGE_ELEMENTAL_FIRE_DESCRIPTION,			// Fire:%d";
	UI_STRING_MESSAGE_ELEMENTAL_WATER_DESCRIPTION,			// Water:%d";
	UI_STRING_MESSAGE_ELEMENTAL_EARTH_DESCRIPTION,			// Earth:%d";
	UI_STRING_MESSAGE_ELEMENTAL_WIND_DESCRIPTION,			// Wind:%d";
	
	UI_STRING_MESSAGE_DESC_EP,								// EP :

	UI_STRING_MESSAGE_PREV_MAP,								
	UI_STRING_MESSAGE_NEXT_MAP,								
	UI_STRING_MESSAGE_CLOSE_HORN,							
	
	UI_STRING_MESSAGE_DESC_ATTACK_SPEED,					

	STRING_STATUS_EP_MAX_1,									
	STRING_STATUS_EP_MAX_2,									
	UI_STRING_MESSAGE_DESC_MAGIC_DAMAGE,					
	
	STRING_MESSAGE_OPEN_LAIR,								
	STRING_MESSAGE_CLOSED_LAIR,								
	STRING_MESSAGE_LEFT_TIME_LAIR,							
	
	STRING_MESSAGE_CONTRACT_GNOMES_HORN,					
	STRING_MESSAGE_CONTRACT_GNOMES_HORN_OK,					
	
	STRING_MESSAGE_CANNOT_DOWN_SKILL,						
	STRING_MESSAGE_NOT_ENOUGH_MONEY_FOR_DOWN_SKILL,			
	UI_STRING_MESSAGE_CONFIRM_DOWN_SKILL,					
	STRING_MESSAGE_SUCCESS_CHANGE,							
	UI_STRING_MESSAGE_WITHDRAW_POINT,						
	UI_STRING_MESSAGE_DESC_DOWN_SKILL,						
	STRING_MESSAGE_NOT_OUSTERS,								
	STRING_MESSAGE_TOO_LOW_SKILL_LEVEL,						
	STRING_MESSAGE_TOO_HIGH_SKILL_LEVEL,					
	STRING_MESSAGE_INVALID_SKILL,							
	STRING_MESSAGE_NOT_LEARNED_SKILL,						
	UI_STRING_MESSAGE_CONFIRM_UP_TO_LAST_SKILL_LEVEL,			
	STRING_MESSAGE_CANNOT_USE_OUSTERS,						
	STRING_MESSAGE_MIXING_FORGE_FAILED_SAME_OPTION_GROUP,	
	UI_STRING_MESSAGE_CONFIRM_CHANGE_SEX,					
	STRING_MESSAGE_CANNOT_CHANGE_SEX_BY_WEAR,				
	STRING_MESSAGE_CANNOT_CHANGE_SEX_BY_COUPLE,				

	UI_STRING_MESSAGE_EVENT_QUEST2_1,						
	UI_STRING_MESSAGE_EVENT_QUEST2_2,						
	UI_STRING_MESSAGE_EVENT_QUEST2_3,						
	UI_STRING_MESSAGE_EVENT_QUEST2_4,						
	UI_STRING_MESSAGE_EVENT_QUEST2_5,						

	STRING_MESSAGE_SELECT_MINI_GAME,						
	STRING_MESSAGE_SELECT_ARROW_TILES,						
	STRING_MESSAGE_SELECT_CRAZY_MINE,						

	STRING_MESSAGE_GET_RIFINIUM,							
	UI_STRING_MESSAGE_QUEST_STATUS_ARROW_TILES,				// Arrow Tiles
	UI_STRING_MESSAGE_QUEST_STATUS_CRAZY_MINE,				// Crazy Mine
	UI_STRING_MESSAGE_SUCCESS_MINIGAME,						// "All Stage Clear!"

	STRING_MESSAGE_GUILD_REGIST_FAIL_ALREADY_JOIN,		
	STRING_MESSAGE_GUILD_REGIST_FAIL_QUIT_TIMEOUT,		
	STRING_MESSAGE_GUILD_REGIST_FAIL_CANCEL_TIMEOUT,		
	STRING_MESSAGE_GUILD_REGIST_FAIL_LEVEL,				
	STRING_MESSAGE_GUILD_REGIST_FAIL_MONEY,				
	STRING_MESSAGE_GUILD_REGIST_FAIL_FAME,				
	STRING_MESSAGE_GUILD_REGIST_FAIL_NAME,				
	STRING_MESSAGE_GUILD_REGIST_FAIL_DENY,				

	STRING_MESSAGE_GUILD_STARTING_FAIL_ALREADY_JOIN,		
	STRING_MESSAGE_GUILD_STARTING_FAIL_QUIT_TIMEOUT,		
	STRING_MESSAGE_GUILD_STARTING_FAIL_CANCEL_TIMEOUT,	
	STRING_MESSAGE_GUILD_STARTING_FAIL_LEVEL,				
	STRING_MESSAGE_GUILD_STARTING_FAIL_MONEY,				
	STRING_MESSAGE_GUILD_STARTING_FAIL_FAME,				
	
	UI_STRING_MESSAGE_CLICK_TO_SHOW_DETIAL,					
	
	STRING_MESSAGE_OUSTERS,									
	
	STRING_MESSAGE_EVENT_FLAG_WAR_READY,					
	STRING_MESSAGE_EVENT_FLAG_WAR_START,					
	STRING_MESSAGE_EVENT_FLAG_WAR_FINISH,					
	STRING_MESSAGE_EVENT_FLAG_WAR_WINNER,					
	STRING_MESSAGE_EVENT_FLAG_WILL_POUR_ITEM_AFTER_3MIN,	
	STRING_MESSAGE_EVENT_FLAG_POURED_ITEM,					

	UI_STRING_MESSAGE_GET_EVENT_FLAG_STATUS,				
	
	UI_STRING_MESSAGE_MUTE,									
	STRING_MESSAGE_CANNOT_MOVE_SAFETY_ZONE_FLAG,			
	STRING_MESSAGE_CANNOT_DROP_ITEM_BY_FLAG,				
	STRING_MESSAGE_POUR_ITEM_AFTER_SECOND,					

	UI_STRING_MESSAGE_CANNOT_ACTION_MOTORCYCLE_FLAG,		
	
	UI_STRING_MESSAGE_TEAM_INFO_GUILD_NAME,					// Guild Name : %s"
	UI_STRING_MESSAGE_TEAM_INFO_GUILD_INTRODUCTION,			// Guild Introduction : "
	UI_STRING_MESSAGE_OTHER_INFO_GUILD_NAME,				
	UI_STRING_MESSAGE_NOT_JOIN_ANY_GUILD,					
	
	UI_STRING_MESSAGE_USE_ETERNITY_FOR_RESURRECT,			
	UI_STRING_MESSAGE_CANNOT_RELOAD_BY_VIVID_MAGAZINE,		
	STRING_MESSAGE_RESURRECT_AFTER_SECONDS,					
	
	STRING_MESSAGE_CANNOT_TRADE_SUMMON_SYLPH,				
	STRING_MESSAGE_CANNOT_USE_SUMMON_SYLPH,					
	
	STRING_MESSAGE_MODIFY_SKILL_LEVEL_1,					
	STRING_MESSAGE_MODIFY_SKILL_LEVEL_2,					

	// 2003.09.29
	UI_STRING_MESSAGE_GO_TO_BEGINNER_ZONE,					
	UI_STRING_MESSAGE_LEFT_PREMIUM_DAYS,					
	UI_STRING_MESSAGE_NOT_PREMIUM_USER,						
	UI_STRING_MESSAGE_EXPIRE_PREMIUM_SERVICE_TODAY,			

	STRING_MESSAGE_EXPIRE_PREMIUM_SERVICE_MESSAGE_1,		
	STRING_MESSAGE_EXPIRE_PREMIUM_SERVICE_MESSAGE_2,		
	STRING_MESSAGE_EXPIRE_PREMIUM_SERVICE_MESSAGE_3,		

	STRING_MESSAGE_LEVEL_WAR_ZONE_NAME,						

	UI_STRING_MESSAGE_SWEEPER_BONUS_1,						
	UI_STRING_MESSAGE_SWEEPER_BONUS_2,						
	UI_STRING_MESSAGE_SWEEPER_BONUS_3,						
	UI_STRING_MESSAGE_SWEEPER_BONUS_4,						
	UI_STRING_MESSAGE_SWEEPER_BONUS_5,						
	UI_STRING_MESSAGE_SWEEPER_BONUS_6,						
	UI_STRING_MESSAGE_SWEEPER_BONUS_7,						
	UI_STRING_MESSAGE_SWEEPER_BONUS_8,						
	UI_STRING_MESSAGE_SWEEPER_BONUS_9,						
	UI_STRING_MESSAGE_SWEEPER_BONUS_10,						
	UI_STRING_MESSAGE_SWEEPER_BONUS_11,						
	UI_STRING_MESSAGE_SWEEPER_BONUS_12,						

	UI_STRING_MESSAGE_JOIN_LEVEL_WAR,						
	
	UI_STRING_MESSAGE_CLICK_TO_WARP_REGEN_TOWER,			

	UI_STRING_MESSAGE_BLOOD_BIBLE_STATUS_HAS_OUSTERS,		
	UI_STRING_MESSAGE_BLOOD_BIBLE_STATUS_OUSTERS,			

	UI_STRING_MESSAGE_MAILBOX,									
	UI_STRING_MESSAGE_CLOSE_MAILBOX,							
	UI_STRING_MESSAGE_MAILBOX_TAB_MAIL,							
	UI_STRING_MESSAGE_MAILBOX_TAB_HELP,							
	UI_STRING_MESSAGE_MAILBOX_TAB_MEMO,							

	STRING_MESSAGE_SUCCESS_CHANGED_BAT_COLOR,				

	UI_STRING_MESSAGE_LEVEL_WAR,							
	
	UI_STRING_MESSAGE_LEFT_FAMILY_DAYS,						
	UI_STRING_MESSAGE_EXPIRE_FAMILY_TODAY,					

	UI_STRING_MESSAGE_TOO_FAR,								

	UI_STRING_MESSAGE_PET_DESC_DURABILITY,					
	UI_STRING_MESSAGE_PET_ATTR,								
	
	UI_STRING_MESSAGE_SHOW_PET_INFO_WINDOW,					
	
	STRING_MESSAGE_ENCHANT_FAIL,							
	UI_STRING_MESSAGE_PET_DESC_DURABILITY_2,				

	UI_STRING_MESSAGE_PET_RESSURECT,						
	UI_STRING_MESSAGE_CLOSE_PET_INFO,						
	
	UI_STRING_MESSAGE_CAN_ENCHANT_PET,						
	UI_STRING_MESSAGE_CANNOT_ENCHANT_PET,					

	STRING_MESSAGE_NEW_PET_LEVEL_1,							
	STRING_MESSAGE_NEW_PET_LEVEL_2,							

	STRING_MESSAGE_OPTION_NAME_LUCK_3,						
	STRING_MESSAGE_OPTION_NAME_LUCK_4,						

	STRING_MESSAGE_OPTION_NAME_ATTR_3,						
	STRING_MESSAGE_OPTION_NAME_ATTR_4,						

	STRING_MESSAGE_PET_DIE_WARNING,							
	STRING_MESSAGE_PET_REQUEST_REFILL,						
	STRING_MESSAGE_PET_DIE,									
	STRING_MESSAGE_PET_SUMMON,								
	STRING_MESSAGE_PET_CAN_GET_ATTR,						
	STRING_MESSAGE_PET_GAMBLE_OK,							
	STRING_MESSAGE_PET_GAMBLE_DESC,							
	STRING_MESSAGE_PET_GAMBLE_DESC_TEEN,					
	STRING_MESSAGE_PET_CAN_GET_OPTION,						
	UI_STRING_MESSAGE_HPBAR_EXP_DESCRIPTION_NEW,			
	STRING_MESSAGE_PET_GAMBLE_FAIL,							

	STRING_MESSAGE_OPTION_ENAME_LUCK_3,						
	STRING_MESSAGE_OPTION_ENAME_LUCK_4,						

	STRING_MESSAGE_OPTION_ENAME_ATTR_3,						
	STRING_MESSAGE_OPTION_ENAME_ATTR_4,						

	UI_STRING_MESSAGE_CAN_PET_REVIVAL,						
	UI_STRING_MESSAGE_CANNOT_PET_REVIVAL,					

	UI_STRING_MESSAGE_PET_CAN_CUT_HEAD,						
	UI_STRING_MESSAGE_PET_CANNOT_CUT_HEAD,					
	
	UI_STRING_MESSAGE_REMOVE_PET_OPTION,					

	STRING_MESSAGE_CANNOT_EVENT_GIFT_BOX,

	STRING_MESSAGE_EVENT_NETMARBLE_1,
	STRING_MESSAGE_EVENT_NETMARBLE_2,
	STRING_MESSAGE_EVENT_NETMARBLE_3,
	STRING_MESSAGE_EVENT_NETMARBLE_4,
	
	UI_STRING_MESSAGE_CAN_USE_PET_FOOD,
	UI_STRING_MESSAGE_DETACH_PET_FOOD,
	UI_STRING_MESSAGE_USE_PET_FOOD,
	UI_STRING_MESSAGE_CANNOT_DETACH,

	UI_STRING_MESSAGE_COMPUTER_STRING_0,
	UI_STRING_MESSAGE_COMPUTER_STRING_1,
	UI_STRING_MESSAGE_COMPUTER_STRING_2,
	UI_STRING_MESSAGE_COMPUTER_STRING_3,
	UI_STRING_MESSAGE_COMPUTER_STRING_4,
	UI_STRING_MESSAGE_COMPUTER_STRING_5,
	UI_STRING_MESSAGE_COMPUTER_STRING_6,
	UI_STRING_MESSAGE_COMPUTER_STRING_7,
	UI_STRING_MESSAGE_COMPUTER_STRING_8,
	UI_STRING_MESSAGE_COMPUTER_STRING_9,
	UI_STRING_MESSAGE_COMPUTER_STRING_10,
	UI_STRING_MESSAGE_COMPUTER_STRING_11,
	UI_STRING_MESSAGE_COMPUTER_STRING_12,
	UI_STRING_MESSAGE_COMPUTER_STRING_13,
	UI_STRING_MESSAGE_COMPUTER_STRING_14,
	UI_STRING_MESSAGE_COMPUTER_STRING_15,
	UI_STRING_MESSAGE_COMPUTER_STRING_16,
	UI_STRING_MESSAGE_COMPUTER_STRING_17,
	UI_STRING_MESSAGE_COMPUTER_STRING_18,
	UI_STRING_MESSAGE_COMPUTER_STRING_19,
	UI_STRING_MESSAGE_COMPUTER_STRING_20,
	UI_STRING_MESSAGE_COMPUTER_STRING_21,
	UI_STRING_MESSAGE_COMPUTER_STRING_22,
	UI_STRING_MESSAGE_COMPUTER_STRING_23,
	UI_STRING_MESSAGE_COMPUTER_STRING_24,
	UI_STRING_MESSAGE_COMPUTER_STRING_25,
	UI_STRING_MESSAGE_COMPUTER_STRING_26,
	UI_STRING_MESSAGE_COMPUTER_STRING_27,
	UI_STRING_MESSAGE_COMPUTER_STRING_28,
	UI_STRING_MESSAGE_COMPUTER_STRING_29,

	UI_STRING_MESSAGE_BOOK_NAME_0,
	UI_STRING_MESSAGE_BOOK_NAME_1,
	UI_STRING_MESSAGE_BOOK_NAME_2,
	UI_STRING_MESSAGE_BOOK_NAME_3,
	UI_STRING_MESSAGE_BOOK_NAME_4,
	UI_STRING_MESSAGE_BOOK_NAME_5,
	UI_STRING_MESSAGE_BOOK_NAME_6,
	UI_STRING_MESSAGE_BOOK_NAME_7,
	UI_STRING_MESSAGE_BOOK_NAME_8,
	UI_STRING_MESSAGE_BOOK_NAME_9,
	UI_STRING_MESSAGE_BOOK_NAME_10,
	UI_STRING_MESSAGE_BOOK_NAME_11,
	UI_STRING_MESSAGE_BOOK_NAME_12,
	UI_STRING_MESSAGE_BOOK_NAME_13,
	UI_STRING_MESSAGE_BOOK_NAME_14,
	UI_STRING_MESSAGE_BOOK_NAME_15,
	UI_STRING_MESSAGE_BOOK_NAME_16,
	UI_STRING_MESSAGE_BOOK_NAME_17,
	UI_STRING_MESSAGE_BOOK_NAME_18,
	UI_STRING_MESSAGE_BOOK_NAME_19,
	UI_STRING_MESSAGE_BOOK_NAME_20,

	//Monster Name
	UI_STRING_MESSAGE_MONSTER_ENAME_TNDEAD,				
	UI_STRING_MESSAGE_MONSTER_ENAME_ARKHAN,				
	UI_STRING_MESSAGE_MONSTER_ENAME_ESTROIDER,		
	UI_STRING_MESSAGE_MONSTER_ENAME_GOLEMER,				
	UI_STRING_MESSAGE_MONSTER_ENAME_DARKSCREAMER,		
	UI_STRING_MESSAGE_MONSTER_ENAME_DEADBODY,			
	UI_STRING_MESSAGE_MONSTER_ENAME_MODERAS,				
	UI_STRING_MESSAGE_MONSTER_ENAME_VANDALIZER,			
	UI_STRING_MESSAGE_MONSTER_ENAME_DIRTYSTRIDER,		
	UI_STRING_MESSAGE_MONSTER_ENAME_HELLWIZARD,			
	UI_STRING_MESSAGE_MONSTER_ENAME_TNSOUL,				
	UI_STRING_MESSAGE_MONSTER_ENAME_IRONTEETH,			
	UI_STRING_MESSAGE_MONSTER_ENAME_REDEYE,				
	UI_STRING_MESSAGE_MONSTER_ENAME_CRIMSONSLAUGTHER,	
	UI_STRING_MESSAGE_MONSTER_ENAME_HELLGUARDIAN,		
	UI_STRING_MESSAGE_MONSTER_ENAME_SOLDIER,				
	UI_STRING_MESSAGE_MONSTER_ENAME_RIPPER,				
	UI_STRING_MESSAGE_MONSTER_ENAME_BIGFANG,				
	UI_STRING_MESSAGE_MONSTER_ENAME_LORDCHAOS,			
	UI_STRING_MESSAGE_MONSTER_ENAME_CHAOSGUARDIAN,		
	UI_STRING_MESSAGE_MONSTER_ENAME_HOBBLE,				
	UI_STRING_MESSAGE_MONSTER_ENAME_CHAOSNIGHT,			
	UI_STRING_MESSAGE_MONSTER_ENAME_WIDOWS,				
	UI_STRING_MESSAGE_MONSTER_ENAME_KID,					
	UI_STRING_MESSAGE_MONSTER_ENAME_SHADOWWING,			

	UI_STRING_MESSAGE_HAN_DOMAIN_BLADE, 
	UI_STRING_MESSAGE_HAN_DOMAIN_SWORD, 
	UI_STRING_MESSAGE_HAN_DOMAIN_ENCHANT, 
	UI_STRING_MESSAGE_HAN_DOMAIN_GUN, 
	UI_STRING_MESSAGE_HAN_DOMAIN_HEAL, 
	UI_STRING_MESSAGE_HAN_DOMAIN_ETC, 
	UI_STRING_MESSAGE_HAN_DOMAIN_VAMPIRE, 
	UI_STRING_MESSAGE_HAN_DOMAIN_OUSTERS, 
	
	UI_STRING_MESSAGE_ENG_DOMAIN_ETC, // ]="Etc";
	UI_STRING_MESSAGE_ENG_DOMAIN_VAMPIRE, // ]="Vampire";
	UI_STRING_MESSAGE_ENG_DOMAIN_OUSTERS, // ]="Ousters";
	
	STRING_MESSAGE_SOUL_STONE,
	
	UI_STRING_MESSAGE_CAN_PET_MUTANT,	
	UI_STRING_MESSAGE_CANNOT_PET_MUTANT,	
	UI_STRING_MESSAGE_PET_MUTANT,

	// 2004, 03, 26 sobeit add start
	STRING_ERROR_CANNOT_AUTHORIZE_BILLING,   
    STRING_ERROR_CANNOT_CREATE_PC_BILLING,    
	// 2004, 03, 26 sobeit add end
	
	UI_STRING_MESSAGE_DESC_PET_DEAD_DAY,	

	// 2004, 04, 3 sobeit add start
	UI_STRING_MESSAGE_DESC_LUCKY,	
	// 2004, 04, 3 sobeit add end

	// 2004, 4, 13 sobeit add start
	UI_STRING_MESSAGE_PET_QUEST_NPC_SLAYER, 
	UI_STRING_MESSAGE_PET_QUEST_NPC_VAMPIRE, 
	UI_STRING_MESSAGE_PET_QUEST_NPC_OUSTERS,

	UI_STRING_MESSAGE_PET_QUEST_SLAYER,		
	UI_STRING_MESSAGE_PET_QUEST_VAMPIRE,	
	UI_STRING_MESSAGE_PET_QUEST_OUSTERS,	
	UI_STRING_MESSAGE_PET_QUEST_CLEAR,		

	UI_STRING_MESSAGE_CAN_3RD_ENCHANT_PET, 
	UI_STRING_MESSAGE_CANNOT_3RD_ENCHANT_PET, 
	STRING_MESSAGE_PET_3RD_GAMBLE_FAIL,
	STRING_MESSAGE_PET_3RD_GAMBLE_OK,
	// 2004, 4, 13 sobeit add end
	
	UI_STRING_MESSAGE_CANNOT_SUMMON_2ND_PET, 
	STRING_MESSAGE_SEARCHING_MINE,			
	UI_STRING_MESSAGE_CANNOT_MIXING_GRADE_VALUE, 

	// 2004, 4, 29 sobeit add start
	STRING_MESSAGE_MINIGAME_GAME_OVER,	//"game over";
	STRING_MESSAGE_MINIGAME_ALL_STAGE_CLEAR, // "All stage clear";
	// 2004, 4, 29 sobeit add end

	// 2004, 5, 6, sobeit add start
	UI_STRING_MESSAGE_SELECT_QUEST_OUSTERS, 
	// 2004, 5, 6, sobeit add end
	// 2004, 6, 22 By Csm 
	STRING_ERROR_CHILDGUARD_DENYED, // "User who age under 18 will not able to play after 22.00 O'clock.";
	// end 
	STRING_MESSAGE_KEEP_PETITEM,
	STRING_MESSAGE_GET_KEEP_PETITEM,
	
	STRING_MESSAGE_EXIST_ITEM_ALREADY, 

	UI_STRING_MESSAGE_ITEM_GRADE , 
	UI_STRING_MESSAGE_ITEM_GRADE_DESC, 

	UI_STRING_MESSAGE_SMS_SEND_OK,
	UI_STRING_MESSAGE_SMS_SEND_FAIL,
	UI_STRING_MESSAGE_SMS_ADD_FAIL,
	UI_STRING_MESSAGE_SMS_DELETE_FAIL,
	
	UI_STRING_MESSAGE_SMS_FAIL_MAX_NUM_EXCEEDED,
	UI_STRING_MESSAGE_SMS_FAIL_INVALID_DATA,
	UI_STRING_MESSAGE_SMS_FAIL_NO_SUCH_EID,
	UI_STRING_MESSAGE_SMS_FAIL_NOT_ENOUGH_CHARGE,
	UI_STRING_MESSAGE_SMS_WINDOW,//"SMS(SMS Widow)";
	UI_STRING_HELP_SMS_SEND,
	UI_STRING_HELP_SMS_VIEW_LIST,
	UI_STRING_HELP_SMS_WINDOW,
	UI_STRING_HELP_SMS_ADDSEND,
	UI_STRING_HELP_SMS_DELETE,
	UI_STRING_HELP_SMS_NEW,

	UI_STRING_MESSAGE_USE_SMSITEM, 
	UI_STRING_MESSAGE_NAMING_WINDOW, //"NAMING(NAMING Window)";
	UI_STRING_MESSAGE_CHANGE_PET_NICKNAME,
	UI_STRING_MESSAGE_CHANGE_PLAYER_NICKNAME,
	UI_STRING_MESSAGE_ADD_PLAYER_NICKNAME,
	UI_STRING_MESSAGE_SELECT_PLAYER_NICKNAME,
	UI_STRING_MESSAGE_NICKNAME_CHANGE_OK, 
	UI_STRING_MESSAGE_NICKNAME_SELECT_FAIL_FORCED,
	UI_STRING_MESSAGE_USE_NAMINGITEM, 

	UI_STRING_MESSAGE_PET_NAMING_SUMMON,
	UI_STRING_MESSAGE_PET_NAMING_WOLVERINE,
	UI_STRING_MESSAGE_FAIL_SEARCH_ITEM,

	UI_STRING_CORE_ZAP_BLACK,
	UI_STRING_CORE_ZAP_RED,
	UI_STRING_CORE_ZAP_BLUE,
	UI_STRING_CORE_ZAP_GREEN,

	UI_STRING_CORE_ZAP_REWARD_ALL_STAT,
	UI_STRING_CORE_ZAP_REWARD_ALL_REG,
	// 2004, 7,1 sobeit add start

	UI_STRING_MESSAGE_DESC_DIALOG_OPTION_EMPTY2, //"\t       %s";
	UI_STRING_MESSAGE_DESC_DIALOG_OPTION2, 

	UI_STRING_GQUEST_CAN_NOT,
	UI_STRING_GQUEST_CAN_ACCEPT,
	UI_STRING_GQUEST_DOING,
	UI_STRING_GQUEST_SUCCESS,
	UI_STRING_GQUEST_COMPLETE,
	UI_STRING_GQUEST_FAIL,
	UI_STRING_GQUEST_CAN_REPLAY,
	UI_STRING_GQUEST_MISSION,

	UI_STRING_GQUEST_BUTTON_ACCEPT,
	UI_STRING_GQUEST_BUTTON_GIVEUP,
	UI_STRING_GQUEST_TAB_PROCESS,
	UI_STRING_GQUEST_TAB_COMPLETE,

	UI_STRING_NOTICE_EVENT_GOLD_MEDALS,
	STRING_ERROR_KEY_EXPIRED,
	STRING_ERROR_NOT_FOUND_KEY,

	UI_STRING_GQUEST_UPDATE, 

	UI_STRING_CHANGE_EVENTITEM_PRICE,
	
	STRING_MESSAGE_TOO_MANY_GUILD_REGISTERED,
	STRING_MESSAGE_REINFORCE_DENYED,
	STRING_MESSAGE_ALREADY_REINFORCE_ACCEPTED,
	STRING_MESSAGE_NO_WAR_REGISTERED,
	STRING_MESSAGE_CANNOT_ACCEPT,
	STRING_MESSAGE_ACCEPT_OK,
	
	STRING_MESSAGE_CANNOT_DENY,							
    STRING_MESSAGE_DENY_OK,                               

	STRING_MESSAGE_SIEGE_POTAL_200,
	STRING_MESSAGE_SIEGE_POTAL_201,
	STRING_MESSAGE_SIEGE_POTAL_202,
	STRING_MESSAGE_SIEGE_POTAL_203,
	STRING_MESSAGE_LOGIN_ERROR_NONPK, 

	STRING_MESSAGE_DAUM_EVENT_1,
	STRING_MESSAGE_DAUM_EVENT_2,
	STRING_MESSAGE_DAUM_EVENT_3,
	STRING_MESSAGE_DAUM_EVENT_BOX1,
	STRING_MESSAGE_DAUM_EVENT_BOX2,
	STRING_MESSAGE_DAUM_EVENT_BOX3,
	STRING_MESSAGE_DAUM_EVENT_BOX4,
	STRING_MESSAGE_DAUM_EVENT_BOX5,
	STRING_MESSAGE_DAUM_EVENT_BOX6,
	STRING_MESSAGE_DAUM_EVENT_BOX7,
	STRING_MESSAGE_DAUM_EVENT_BOX8,
		
	UI_STRING_MESSAGE_RANK_BONUS_PERCEPTION,
    UI_STRING_MESSAGE_RANK_BONUS_STONE_OF_SAGE,
    UI_STRING_MESSAGE_RANK_BONUS_FOOT_OF_RANGER,
    UI_STRING_MESSAGE_RANK_BONUS_WARRIORS_FIST,

    UI_STRING_MESSAGE_RANK_BONUS_ACID_INQUIRY,
    UI_STRING_MESSAGE_RANK_BONUS_BLOODY_INQUIRY,
    UI_STRING_MESSAGE_RANK_BONUS_CURSE_INQUIRY,
    UI_STRING_MESSAGE_RANK_BONUS_POISON_INQUIRY,
	UI_STRING_MESSAGE_RANK_BONUS_INQUIRY_MASTERY,

    UI_STRING_MESSAGE_RANK_BONUS_POWER_OF_SPIRIT,
    UI_STRING_MESSAGE_RANK_BONUS_WIND_OF_SPIRIT,
    UI_STRING_MESSAGE_RANK_BONUS_PIXIES_EYES,
    UI_STRING_MESSAGE_RANK_BONUS_GROUND_OF_SPIRIT,
    UI_STRING_MESSAGE_RANK_BONUS_FIRE_OF_SPIRIT,

    UI_STRING_MESSAGE_RANK_BONUS_EVOLUTION_IMMORTAL_HEART,
    UI_STRING_MESSAGE_RANK_BONUS_BEHEMOTH_ARMOR_2,
    UI_STRING_MESSAGE_RANK_BONUS_DRAGON_EYE_2,
    UI_STRING_MESSAGE_RANK_BONUS_EVOLUTION_RELIANCE_BRAIN,
    UI_STRING_MESSAGE_RANK_BONUS_HEAT_CONTROL,

	UI_STRING_MESSAGE_RANK_BONUS_ACID_MASTERY,
    UI_STRING_MESSAGE_RANK_BONUS_BLOODY_MASTERY,
    UI_STRING_MESSAGE_RANK_BONUS_CURSE_MASTERY,
    UI_STRING_MESSAGE_RANK_BONUS_POISON_MASTERY,
    UI_STRING_MESSAGE_RANK_BONUS_SKILL_MASTERY,

    UI_STRING_MESSAGE_RANK_BONUS_SALAMANDERS_KNOWLEDGE,
    UI_STRING_MESSAGE_RANK_BONUS_UNDINES_KNOWLEDGE,
    UI_STRING_MESSAGE_RANK_BONUS_GNOMES_KNOWLEDGE,
	
	UI_STRING_MESSAGE_SIEGE_ATTACK,
	UI_STRING_MESSAGE_SIEGE_DEFENSE,
	
	UI_STRING_MESSAGE_NOT_LOGINED,
	UI_STRING_MESSAGE_GUILD_LIST_ID,
	UI_STRING_MESSAGE_GUILD_LIST_SERVER,
	UI_STRING_MESSAGE_GUILD_LIST_GRADE,

	UI_STRING_MESSAGE_TEAM_COMMAND_WINDOW,
	UI_STRING_MESSAGE_TEAM_LIST_WINDOW,
	UI_STRING_MESSAGE_TEAM_WAIT_LIST_WINDOW,
	UI_STRING_MESSAGE_TEAM_UNION_WINDOW,

	UI_STRING_MESSAGE_CLAN_COMMAND_WINDOW,
	UI_STRING_MESSAGE_CLAN_LIST_WINDOW,
	UI_STRING_MESSAGE_CLAN_WAIT_LIST_WINDOW,
	UI_STRING_MESSAGE_CLAN_UNION_WINDOW,

	UI_STRING_MESSAGE_GUILD_COMMAND_WINDOW,
	UI_STRING_MESSAGE_GUILD_LIST_WINDOW,
	UI_STRING_MESSAGE_GUILD_WAIT_LIST_WINDOW,
	UI_STRING_MESSAGE_GUILD_UNION_WINDOW,

	UI_STRING_MESSAGE_TOTAL_GUILD_DESC1,
	UI_STRING_MESSAGE_TOTAL_GUILD_DESC2,
	UI_STRING_MESSAGE_TOTAL_GUILD_DESC3,
	UI_STRING_MESSAGE_TOTAL_GUILD_ALREADY_IN_UNION,
	UI_STRING_MESSAGE_TOTAL_GUILD_ALREADY_OFFER_SOMETHING,
	UI_STRING_MESSAGE_TOTAL_GUILD_TARGET_IS_NOT_MASTER,   
	UI_STRING_MESSAGE_TOTAL_GUILD_NOT_IN_UNION,
	UI_STRING_MESSAGE_TOTAL_GUILD_MASTER_CANNOT_QUIT,
	UI_STRING_MESSAGE_TOTAL_GUILD_NO_TARGET_UNION,
	UI_STRING_MESSAGE_TOTAL_GUILD_NOT_YOUR_UNION,
	UI_STRING_MESSAGE_TOTAL_GUILD_SOURCE_IS_NOT_MASTER,
	UI_STRING_MESSAGE_TOTAL_GUILD_JOIN_ASK,
	UI_STRING_MESSAGE_TOTAL_GUILD_MESSAGE_OK,
	UI_STRING_MESSAGE_TOTAL_GUILD_MESSAGE_REFUSE,
	UI_STRING_MESSAGE_TOTAL_GUILD_MESSAGE_SUCCESS,
	UI_STRING_MESSAGE_TOTAL_GUILD_LEAVE_ASK,
	UI_STRING_MESSAGE_TOTAL_GUILD_LEAVE_MSG, 
	UI_STRING_MESSAGE_TOTAL_GUILD_LEAVE_MSG2,
	UI_STRING_MESSAGE_TOTAL_GUILD_LEAVE_OK,
	UI_STRING_MESSAGE_TOTAL_GUILD_LEAVE_CANCEL,
	UI_STRING_MESSAGE_TOTAL_GUILD_DEPORT_ASK,
	UI_STRING_MESSAGE_TOTAL_GUILD_DEPORT_OK,		

	UI_STRING_MESSAGE_TOTAL_UNION_JOIN_MSG,
	UI_STRING_MESSAGE_TOTAL_UNION_DEPORT_MSG,
	UI_STRING_MESSAGE_TOTAL_UNION_PENALTY,
	
	UI_STRING_MESSAGE_ASKING_RECALL,
	UI_STRING_LEARN_SKILL_LEVEL,
	UI_STRING_MESSAGE_TOTAL_GUILD_LEAVE_ACCEPT,
	UI_STRING_MESSAGE_TOTAL_GUILD_LEAVE_DENY,

	UI_STRING_MESSAGE_REQUEST_UNION_ERROR_1,
	UI_STRING_MESSAGE_REQUEST_UNION_ERROR_2,
	UI_STRING_MESSAGE_REQUEST_UNION_ERROR_3,
	UI_STRING_MESSAGE_UNION_ERROR_NO_SLOT,
	
	UI_STRING_MESSAGE_EQUIP_BLOOD_BIBLE,
	UI_STRING_MESSAGE_RENT_BLOOD_BIBLE,
	UI_STRING_MESSAGE_RENT_BLOOD_BIBLE2,
	UI_STRING_MESSAGE_RENT_LATER_BLOOD_BIBLE,

	UI_STRING_MESSAGE_RANGER_SAY,//] = "Ranger/";
	UI_STRING_MESSAGE_MODIFY_TAX_OK,
	UI_STRING_MESSAGE_MODIFY_TAX_FAIL,
	UI_STRING_MESSAGE_MODIFY_TAX,
	UI_STRING_MESSAGE_RANGER_SAY2,

	UI_STRING_MESSAGE_REMOVE_CURSE_1,
	UI_STRING_MESSAGE_REMOVE_CURSE_2,
	UI_STRING_MESSAGE_REMOVE_CURSE_3,
	UI_STRING_MESSAGE_REMOVE_CURSE_4,

	STRING_MESSAGE_RACE_WAR_STARTED_IN_OTHER_SERVER,

	UI_STRING_MESSAGE_APPOINT_SUBMASTER, 
	
	UI_STRING_MESSAGE_CAN_SKILL_DELETE,
	UI_STRING_MESSAGE_CANNOT_SKILL_DELETE,

	STRING_MESSAGE_CANNOT_SKILLTREE_DELETE,
	UI_STRING_MESSAGE_TOO_MANY_MEMBER,
	UI_STRING_MESSAGE_CONFIRM_DOWN_SKILL2,

	UI_STRING_MESSAGE_UNION_CHATTING,
	UI_STRING_MESSAGE_SHOW_UNION_CHATTING,
	UI_STRING_MESSAGE_NOT_SHOW_UNION_CHATTING,

	UI_STRING_MESSAGE_USE_SIEGE_FOR_RESURRECT,

	UI_STRING_POWER_JJANG_GET_POINT,
	UI_STRING_POWER_JJANG_POINT,
	UI_STRING_POWER_JJANG_AVAILABLE,
	UI_STRING_POWER_JJANG_NUMBER_1,
	UI_STRING_POWER_JJANG_NUMBER_2,
	UI_STRING_POWER_JJANG_GET_POINT_HELP,
	UI_STRING_POWER_JJANG_EXCHANGE_HELP,
	UI_STRING_POWER_JJANG_REQUEST_OK,

	UI_STRING_POWER_JJANG_ERROR_NO_MEMBER,
	UI_STRING_POWER_JJANG_ERROR_SERVER_ERROR,
	UI_STRING_POWER_JJANG_ERROR_PROCESS_ERROR,
	UI_STRING_POWER_JJANG_ERROR_NO_POINT,
	UI_STRING_POWER_JJANG_ERROR_NO_MATCHING,
	UI_STRING_POWER_JJANG_ERROR_CONNECT,

	UI_STRING_MESSAGE_UTIL,
	UI_STRING_MESSAGE_PERSONAL_STORE,
	UI_STRING_MESSAGE_POWER_JJANG,

	//add by viva for NONKOWNMESSAGE
	UI_STRING_MESSAGE_NONKOWN1,
	UI_STRING_MESSAGE_NONKOWN2,
	//end

	UI_STRING_MESSAGE_SELL_MONEY_IN_DIALOG,	  
	UI_STRING_MESSAGE_PERSNALSHOP_MESSAGE,	  
	UI_STRING_MESSAGE_PERSNALSHOP_OK,	  
	UI_STRING_MESSAGE_PERSNALSHOP_CANCEL,	  
	UI_STRING_MESSAGE_PERSNALSHOP_WRITE_MESSAGE,	
	
	UI_STRING_MESSAGE_CANNOT_FIND_STORE,
	UI_STRING_MESSAGE_STORE_CLOSED,
	UI_STRING_MESSAGE_ITEM_NOT_FOUND,
	UI_STRING_MESSAGE_TOO_MUCH_MONEY,
	UI_STRING_MESSAGE_ALREADY_DISPLAYED,
	UI_STRING_MESSAGE_PERSNAL_DEFAULT_MESSGE,
	
	UI_STRING_MESSAGE_GAMEMONEY_WITH_HANGUL,
	UI_STRING_MESSAGE_ADVANTE_0,
	UI_STRING_MESSAGE_ADVANTE_1,
	UI_STRING_MESSAGE_ADVANTE_2,
	UI_STRING_MESSAGE_ADVANTE_3,
	UI_STRING_MESSAGE_ADVANTE_4,
	UI_STRING_MESSAGE_ADVANTE_5,
	UI_STRING_MESSAGE_ADVANTE_6,
	UI_STRING_MESSAGE_ADVANTE_7,
	UI_STRING_MESSAGE_ADVANTE_8,
	UI_STRING_MESSAGE_ADVANTE_9,
	UI_STRING_MESSAGE_ADVANTE_10,

	UI_STRING_MESSAGE_EQUIP_PDA,
	UI_STRING_MESSAGE_EQUIP_SHOULDER,

	UI_STRING_MESSAGE_EQUIP_DERMIS,
	UI_STRING_MESSAGE_EQUIP_PERSONA,

	UI_STRING_MESSAGE_EQUIP_FASCIA,
	UI_STRING_MESSAGE_EQUIP_MITTEN,
	UI_STRING_MESSAGE_CHINGHO,
	
	UI_STRING_MESSAGE_SWAP_ADVANCEMENT_ITEM,
	UI_STRING_MESSAGE_SWAP_CONFIRM,
	UI_STRING_MESSAGE_SWAP_ERROR,
	UI_STRING_MESSAGE_SWAP_ADVANCEMENT_ITEM_ERROR,

	UI_STRING_MESSAGE_CAMPAIGN_HELP_REQUEST,
	UI_STRING_MESSAGE_CAMPAIGN_HELP_THANKS,
	UI_STRING_MESSAGE_CAMPAIGN_HELP_UNITS_SLAYER,
	UI_STRING_MESSAGE_CAMPAIGN_HELP_UNITS_VAMPIRE,
	UI_STRING_MESSAGE_CAMPAIGN_HELP_UNITS_OUSTERS,

	UI_STRING_MESSAGE_REQUIRE_ADVANCEMENT_LEVEL_0,
	UI_STRING_MESSAGE_REQUIRE_ADVANCEMENT_LEVEL_1,
	UI_STRING_MESSAGE_REQUIRE_ADVANCEMENT_LEVEL_2,
	UI_STRING_MESSAGE_REQUIRE_ADVANCEMENT_LEVEL_3,
	UI_STRING_MESSAGE_REQUIRE_ADVANCEMENT_LEVEL_4,
	UI_STRING_MESSAGE_REQUIRE_ADVANCEMENT_LEVEL_5,
	UI_STRING_MESSAGE_REQUIRE_ADVANCEMENT_LEVEL_6,
	UI_STRING_MESSAGE_REQUIRE_ADVANCEMENT_LEVEL_7,
	UI_STRING_MESSAGE_REQUIRE_ADVANCEMENT_LEVEL_8,
	UI_STRING_MESSAGE_REQUIRE_ADVANCEMENT_LEVEL_9,
	UI_STRING_MESSAGE_REQUIRE_ADVANCEMENT_LEVEL_10,
	
	UI_STRING_MESSAGE_ADVANCEMENT_JOB_BLADE,
	UI_STRING_MESSAGE_ADVANCEMENT_JOB_SWORD,
	UI_STRING_MESSAGE_ADVANCEMENT_JOB_SOLDER,
	UI_STRING_MESSAGE_ADVANCEMENT_JOB_HEAL,
	UI_STRING_MESSAGE_ADVANCEMENT_JOB_ENCHANT,
	UI_STRING_MESSAGE_ADVANCEMENT_JOB_VAMPIRE,
	UI_STRING_MESSAGE_ADVANCEMENT_JOB_COMBAT,
	UI_STRING_MESSAGE_ADVANCEMENT_JOB_EARTH,
	UI_STRING_MESSAGE_ADVANCEMENT_JOB_FIRE,
	UI_STRING_MESSAGE_ADVANCEMENT_JOB_WATER,

	UI_STRING_MESSAGE_DO_NOT_SHOW_PERSNALSHOP_MSG,

	UI_STRING_MESSAGE_REQUEST_GET_EVENT_ITEM,

	UI_STRING_MESSAGE_GET_EVENT_ITEM_RECEIVE_OK,
	UI_STRING_MESSAGE_GET_EVENT_ITEM_RECEIVE_ALREADY,
	UI_STRING_MESSAGE_GET_EVENT_ITEM_RECEIVE_FAIL,
	UI_STRING_MESSAGE_GET_EVENT_ITEM_NOT_EVENT_USER,

	UI_STRING_MESSAGE_GET_EVENT_ITEM_NOTICE,


	UI_STRING_MESSAGE_FAIL_OPEN_WEBPAGE,
	UI_STRING_MESSAGE_CANNOT_USE_ADVANCEMENTCLASS,

	UI_STRING_MESSAGE_CANNOT_USE_HIGH_GRADE,
	UI_STRING_MESSAGE_CANNOT_USE_ADVANCEMENT_ITEM,
	UI_STRING_MESSAGE_CANNOT_USE_OVER_TWO_OPTION,
	STRING_ERROR_IP_DENY,
	UI_STRING_MESSAGE_CHECK_VERSION_ERROR,
	STRING_STATUS_NOT_FIND_SKILL_CRAD,
	UI_STRING_MESSAGE_SYSTEM,
	UI_STRING_MESSAGE_PLAYER_SAY,
	UI_STRING_NO_ITEM_MESSAGE,				
	//add by viva : friend button description
//	UI_STRING_MESSAGE_FRIEND,
//	UI_STRING_MESSAGE_FRIEND_LIST,
//	UI_STRING_MESSAGE_FRIEND_BLACKLIST,
//	UI_STRING_MESSAGE_FRIEND_TAG,
//	UI_STRING_MESSAGE_FRIEND_UP,
//	UI_STRING_MESSAGE_FRIEND_DOWN,
//	UI_STRING_MESSAGE_FRIEND_FIND,
//	UI_STRING_MESSAGE_FRIEND_ADD,
//	UI_STRING_MESSAGE_FRIEND_SETUP,
//	//add by viva : ask_friend_dialog
//	UI_STRING_ASK_FRIEND_REQUEST,
//	UI_STRING_ASK_FRIEND_REFUSE,
//	UI_STRING_ASK_FRIEND_WAIT,
//	UI_STRING_ASK_FRIEND_EXSIT,
//	UI_STRING_ASK_FRIEND_BLACK,
//	UI_STRING_ASK_FRIEND_DELETE,
	//end
	MAX_GAME_STRING,
};



#endif
