#ifndef	__MODIFYDEF_H__
#define	__MODIFYDEF_H__



enum ModifyType {

	MODIFY_BASIC_STR = 0,        
	MODIFY_CURRENT_STR,          
	MODIFY_MAX_STR,              
	MODIFY_STR_EXP_REMAIN,              

	MODIFY_BASIC_DEX,            
	MODIFY_CURRENT_DEX,          
	MODIFY_MAX_DEX,              
	MODIFY_DEX_EXP_REMAIN,              

	MODIFY_BASIC_INT,            
	MODIFY_CURRENT_INT,          
	MODIFY_MAX_INT,              
	MODIFY_INT_EXP_REMAIN,              

	MODIFY_CURRENT_HP,           
	MODIFY_MAX_HP,               

	MODIFY_CURRENT_MP,           
	MODIFY_MAX_MP,               

	MODIFY_MIN_DAMAGE,           
	MODIFY_MAX_DAMAGE,           

	MODIFY_DEFENSE,              
	MODIFY_PROTECTION,           
	MODIFY_TOHIT,                

	MODIFY_VISION,               
	MODIFY_FAME,                 
	MODIFY_GOLD,                 

	MODIFY_SWORD_DOMAIN_LEVEL,   
	MODIFY_SWORD_DOMAIN_EXP_REMAIN,     
	MODIFY_SWORD_DOMAIN_GOAL_EXP,
	MODIFY_BLADE_DOMAIN_LEVEL,   
	MODIFY_BLADE_DOMAIN_EXP_REMAIN,     
	MODIFY_BLADE_DOMAIN_GOAL_EXP,
	MODIFY_HEAL_DOMAIN_LEVEL,    
	MODIFY_HEAL_DOMAIN_EXP_REMAIN,      
	MODIFY_HEAL_DOMAIN_GOAL_EXP, 
	MODIFY_ENCHANT_DOMAIN_LEVEL, 
	MODIFY_ENCHANT_DOMAIN_EXP_REMAIN,   
	MODIFY_ENCHANT_DOMAIN_GOAL_EXP, 
	MODIFY_GUN_DOMAIN_LEVEL,     
	MODIFY_GUN_DOMAIN_EXP_REMAIN,       
	MODIFY_GUN_DOMAIN_GOAL_EXP,  
	MODIFY_ETC_DOMAIN_LEVEL,     
	MODIFY_ETC_DOMAIN_EXP_REMAIN,       
	MODIFY_ETC_DOMAIN_GOAL_EXP,  

	MODIFY_SKILL_LEVEL,          
	MODIFY_LEVEL,                
	MODIFY_EFFECT_STAT,          
	MODIFY_DURATION,             
	MODIFY_BULLET,               
	MODIFY_BONUS_POINT,          
	MODIFY_DURABILITY,           
	MODIFY_NOTORIETY,            
	MODIFY_VAMP_EXP_REMAIN,             

	MODIFY_SILVER_DAMAGE,        
	MODIFY_ATTACK_SPEED,         
	MODIFY_ALIGNMENT,			

	MODIFY_SILVER_DURABILITY,	

	MODIFY_REGEN_RATE,           
	MODIFY_GUILDID,					

	MODIFY_RANK,				 
	MODIFY_RANK_EXP_REMAIN,			 

	MODIFY_OUSTERS_EXP_REMAIN,          
	MODIFY_SKILL_BONUS_POINT,    
	
	MODIFY_ELEMENTAL_FIRE,
	MODIFY_ELEMENTAL_WATER,
	MODIFY_ELEMENTAL_EARTH,
	MODIFY_ELEMENTAL_WIND,
	
	MODIFY_SKILL_EXP,			
	
    MODIFY_PET_HP,
    MODIFY_PET_EXP_REMAIN,               
	
	MODIFY_LAST_TARGET,

	// 2004, 10, 19, sobeit add start
	MODIFY_UNIONID,
	MODIFY_UNIONGRADE,
	// 2004, 10, 19, sobeit add end
	
    MODIFY_ADVANCEMENT_CLASS_LEVEL, 
    MODIFY_ADVANCEMENT_CLASS_GOAL_EXP,  

	MODIFY_MAX
};


#define	MAX_MODIFY		MODIFY_MAX
#define	MODIFY_NULL		0xFFFFFFFF

#endif