FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    libxerces-c-dev \
    libmysqlclient-dev \
    liblua5.1-dev \
    psmisc \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir /home/darkeden
RUN mkdir /home/darkeden/vs
RUN mkdir /home/darkeden/vs/src
RUN mkdir /home/darkeden/vs/log
RUN mkdir /home/darkeden/vs/pid
RUN mkdir /home/darkeden/vs/output

COPY bin /home/darkeden/vs/bin/
COPY data /home/darkeden/vs/data/
COPY docker/conf /home/darkeden/vs/conf/
COPY docker/start-servers.sh /home/darkeden/vs/start-servers.sh

RUN chmod +x /home/darkeden/vs/start-servers.sh

WORKDIR /home/darkeden/vs/bin
